### PR TITLE
[REVIEW] Optimize waveforms

### PR DESCRIPTION
**Pull request by mnicely**
This PR attempts optimize the waveform module

### This PR
```bash
---------- benchmark 'Square': 4 tests -----------4)
Name (time in us)                   Mean          
--------------------------------------------------
test_square_gpu[0.5-16384]       32.3753 (1.0)    
test_square_gpu[0.25-16384]      33.0561 (1.02)   
test_square_cpu[0.5-16384]      251.2782 (7.76)   
test_square_cpu[0.25-16384]     254.5398 (7.86)
--------------------------------------------------
```

### Branch 0.16
```bash
---------- benchmark 'Square': 4 tests -----------4)
Name (time in us)                   Mean          
--------------------------------------------------
test_square_cpu[0.25-16384]     257.9543 (1.0)    
test_square_cpu[0.5-16384]      260.2890 (1.01)   
test_square_gpu[0.25-16384]     466.7852 (1.81)   
test_square_gpu[0.5-16384]      474.1972 (1.84)   
--------------------------------------------------
```

### This PR
```bash
---------- benchmark 'GaussPulse': 4 tests -----------
Name (time in us)                       Mean          
------------------------------------------------------
test_gausspulse_gpu[0.75-16384]      27.5139 (1.0)    
test_gausspulse_gpu[5-16384]         28.1918 (1.02)   
test_gausspulse_cpu[0.75-16384]     394.4248 (14.34)  
test_gausspulse_cpu[5-16384]        450.1640 (16.36)  
------------------------------------------------------
```

### Branch 0.16
```bash
---------- benchmark 'GaussPulse': 4 tests -----------
Name (time in us)                       Mean          
------------------------------------------------------
test_gausspulse_gpu[5-16384]        109.8970 (1.0)    
test_gausspulse_gpu[0.75-16384]     110.6901 (1.01)   
test_gausspulse_cpu[0.75-16384]     394.6945 (3.59)   
test_gausspulse_cpu[5-16384]        454.8667 (4.14)   
------------------------------------------------------
```

### This PR
```bash
-------------- benchmark 'Chirp': 8 tests --------------
Name (time in us)                         Mean          
--------------------------------------------------------
test_chirp_gpu[quad-10-1-6-16384]      63.6777 (1.0)    
test_chirp_gpu[lin-10-1-6-16384]       63.7323 (1.00)   
test_chirp_gpu[hyp-10-1-6-16384]       66.1522 (1.04)   
test_chirp_gpu[log-10-1-6-16384]       73.1456 (1.15)   
test_chirp_cpu[lin-10-1-6-16384]      188.8952 (2.97)   
test_chirp_cpu[hyp-10-1-6-16384]      254.1944 (3.99)   
test_chirp_cpu[log-10-1-6-16384]      393.3425 (6.18)   
test_chirp_cpu[quad-10-1-6-16384]     415.5281 (6.53)   
--------------------------------------------------------
```

### Branch 0.16
```bash
-------------- benchmark 'Chirp': 8 tests --------------
Name (time in us)                         Mean          
--------------------------------------------------------
test_chirp_gpu[lin-10-1-6-16384]      112.1202 (1.0)    
test_chirp_gpu[hyp-10-1-6-16384]      117.7361 (1.05)   
test_chirp_gpu[quad-10-1-6-16384]     131.7041 (1.17)   
test_chirp_gpu[log-10-1-6-16384]      150.1537 (1.34)   
test_chirp_cpu[lin-10-1-6-16384]      181.4057 (1.62)   
test_chirp_cpu[hyp-10-1-6-16384]      246.7961 (2.20)   
test_chirp_cpu[log-10-1-6-16384]      386.3060 (3.45)   
test_chirp_cpu[quad-10-1-6-16384]     400.0489 (3.57)   
--------------------------------------------------------
```

### This PR
```bash
---------- benchmark 'UnitImpulse': 2 tests ----------
Name (time in us)                       Mean          
------------------------------------------------------
test_unit_impulse_cpu[mid-16384]      7.1316 (1.0)    
test_unit_impulse_gpu[mid-16384]     23.3090 (3.27)   
-----------------------------------------------------
```

### Branch 0.16
```bash
---------- benchmark 'UnitImpulse': 2 tests ----------
Name (time in us)                       Mean          
------------------------------------------------------
test_unit_impulse_cpu[mid-16384]      7.6201 (1.0)    
test_unit_impulse_gpu[mid-16384]     76.5246 (10.04)  
------------------------------------------------------
```

### CODE REVIEW

**Comment by GPUtester** [comment]
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

**Comment by awthomp** [comment]
Is this PR ready for review? If so, could you please change the title to [REVIEW]?

**Comment by mnicely** [comment]
> Is this PR ready for review? If so, could you please change the title to [REVIEW]?

Oh no... Good bit of work left :smile:

**Comment by awthomp** [comment]
> > Is this PR ready for review? If so, could you please change the title to [REVIEW]?
> 
> Oh no... Good bit of work left 😄

Oh my bad! I saw the 'request review' tag. Long day!

**Comment by mnicely** [comment]
> > > Is this PR ready for review? If so, could you please change the title to [REVIEW]?
> > 
> > 
> > Oh no... Good bit of work left 😄
> 
> Oh my bad! I saw the 'request review' tag. Long day!

Ready when you are!

**Review by awthomp — APPROVED** [review]

**Pull request merged**
