### PR TITLE
[REVIEW] Implemented convolve1d{2/3}o 'valid', needed={tests,benchmarks,optimizations}

### PR DESCRIPTION
**Pull request by randompast**
…eded={tests,validations,benchmarks,optimizations}

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by awthomp** [comment]
ok to test

**Comment by BradReesWork** [comment]
ok to test

**Comment by GPUtester** [comment]
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

**Comment by randompast** [comment]
I see the note "CHANGELOG.md has not been updated!"

Really, it's just as the commit message:
"Implemented (valid) second and third order convolve as convolve1d2o and convolve1d3o."

**Comment by awthomp** [comment]
Hi @randompast -- just getting some time to look at this PR! To kick off CI/CD, could you please update the changelog and push to the branch you used to submit this PR?

From the head cusignal directory, edit `CHANGELOG.md` and under 0.17 Improvements, type something like: `- PR #270 - Implement higher order convolutions`.

**Comment by randompast** [comment]
Updated, thanks for the feedback @awthomp!

**Review by BradReesWork — APPROVED** [review]

**Comment by BradReesWork** [comment]
@randompast   this is a style issue blocing this PR:

./cusignal/convolution/convolve.py:587:1: W293 blank line contains whitespace
./cusignal/convolution/_convolution_cuda.py:638:15: W292 no newline at end of file

**Pull request merged**
