### PR TITLE
Use pre-commit to enforce Python style checks

### PR DESCRIPTION
**Pull request by charlesbluca**
This PR adds a [pre-commit](https://pre-commit.com/) configuration to this repo to enforce the Python style checks - it also modifies the gpuCI style check to use pre-commit instead of just `isort`.

The pre-commit configuration can probably be expanded to include CUDA style enforcement with `clang-format`, but this seemed like a decent starting point.

### CODE REVIEW

**Comment by awthomp** [comment]
@ajschmidt8 -- You might be best to review and merge this PR, AJ!

**Review by ajschmidt8 — APPROVED** [review]
Approving `ops-codeowner` file changes

**Comment by ajschmidt8** [comment]
@awthomp, this PR looks good. It will still require an approval from you to satisfy the `cusignal-python-codeowners` review requirements before it can be merged.

**Review by awthomp — APPROVED** [review]

**Comment by ajschmidt8** [comment]
@charlesbluca, let me know if this is all set to merge. feel free to merge if you have permissions

**Comment by charlesbluca** [comment]
@gpucibot merge

**Comment by charlesbluca** [comment]
@ajschmidt8 yeah think you or @awthomp will need to merge this one in

**Comment by charlesbluca** [comment]
Actually, totally forgot that I should merge in the latest changes

**Comment by ajschmidt8** [comment]
@gpucibot merge

**Pull request merged**
