### PR TITLE
[REVIEW] BUG Fix gausspulse (False, False)

### PR DESCRIPTION
**Pull request by mnicely**
While experimenting with CuPy I discovered an error with `gausspulse`.

This PR does the following
1. Implements a fix
2. Adds tests parameters
3. Applies `sincos` math function for performance (Minor ~5%)

### CODE REVIEW

**Comment by GPUtester** [comment]
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

**Comment by awthomp** [comment]
@mnicely - It looks like this PR touches functions beyond the gausspulse; most being with a `cp.asnumpy()` call on test data. What's going on here?

**Comment by mnicely** [comment]
I must have branched from the wrong starting point...
Let me figure out how to fix

**Comment by mnicely** [comment]
It'll be easiest to wait on #271 and merge. Then I'll change back to review.

**Comment by mnicely** [comment]
@awthomp How about now? 

The only change in test files is formatting.

**Review by awthomp — APPROVED** [review]

**Pull request merged**
