### PR TITLE
[REVIEW] Add missing pytest 

### LINKED ISSUE #206: [FEA] Add missing tests for various functions
We need to add test/benchmarks for various functions:

List:
1. test_acoustics
a. rceps
b. cceps_unwrap
c. cceps
2. test_bsplines
a. gauss_spline
b. cubic
c. quadratic
d. cspline1d
3. test_filter_design
a. kaiser_beta
b. kaiser_atten
c. cmplx_sort
4. test_filtering
a. lfiltic
b. detrend
c. freq_shift
d. channelizer
5. test_peak_finding
a. argrelmin
b. argrelmax
c.argrelextrema
6. test_spectral_analysis
a. vectorstrength
7. test_wavelets
a. qmf
8. test_io (NEW)
a. reader
b. writer
9. test_estimation (NEW)
a. kalman_filter

### PR DESCRIPTION
**Pull request by z-ryan1**
Closes #206 

### Info
This PR is to add all missing functions to pytest 

List:

- [ ] **test_acoustics**
  - [x] real_cepstrum
  - [ ] ~~cceps_unwrap~~
  - [x] complex_cepstrum
- [ ] **test_bsplines**
  - [x] gauss_spline
  - [x] cubic
  - [x] quadratic
  - [x] cspline1d
- [ ] **test_filter_design**
  - [x] kaiser_beta
  - [x] kaiser_atten
  - [x] cmplx_sort
- [ ] **test_filtering**
  - [ ] ~~lfiltic~~ (Removed #246)
  - [x] detrend
  - [x] freq_shift (NEW)
  - [x] channelizer
- [ ] **test_peak_finding**
  - [x] argrelmin
  - [x] argrelmax
  - [x] argrelextrema
- [ ] **test_spectral_analysis**
  - [x] vectorstrength
- [ ] **test_wavelets**
  - [x] qmf (Added #235)
- [ ] **test_io (NEW)**
  - [ ] ~~reader~~ (Move to new PR)
  - [ ] ~~writer~~ (Move to new PR)
- [ ] **test_estimation (NEW)**
  - [ ] ~~kalman_filter~~ (Move to new PR)

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by awthomp** [comment]
ok to test

**Comment by awthomp** [comment]
@BradReesWork -- I filed an ops ticket for @z-ryan1 to have write access to cuSignal, but it looks like her PRs still need admin verification to start CI. I've done `ok to test` and `add to whitelist` on this and other PRs, but looks like something might be hung??? Can you and @mnicely investigate while I'm out on leave? Thanks!

**Review by awthomp — APPROVED** [review]

**Comment by awthomp** [comment]
Loving this goal of 100% test coverage! Great work, @z-ryan1!

**Comment by mnicely** [comment]
@awthomp We need to think about if we can support `io/reader`, `io/writer`, and `estimation/kalman_filter` in CI testing.

reader and writer required an input file. We could do this be creating random data in the test??

The kalman filter baseline CPU is hosted in https://filterpy.readthedocs.io/en/latest/. We would have to modify CI to install the filterpy conda package.

**Comment by mnicely** [comment]
@z-ryan1 You will need this code for the channelizer CPU version

```python
def channelize_poly_cpu(x, h, n_chans):
    """
    Polyphase channelize signal into n channels
    Parameters
    ----------
    x : array_like
        The input data to be channelized
    h : array_like
        The 1-D input filter; will be split into n
        channels of int number of taps
    n_chans : int
        Number of channels for channelizer
    Returns
    ----------
    yy : channelized output matrix
    Notes
    ----------
    Currently only supports simple channelizer where channel
    spacing is equivalent to the number of channels used
    """

    # number of taps in each h_n filter
    n_taps = int(len(h) / n_chans)

    # number of outputs
    n_pts = int(len(x) / n_chans)

    dtype = cp.promote_types(x.dtype, h.dtype)

    # order F if input from MATLAB
    hh = np.matrix(np.reshape(h, (n_taps, n_chans)), dtype=dtype).T
    vv = np.empty(n_chans, dtype=dtype)

    if x.dtype == np.float32 or x.dtype == np.complex64:
        yy = np.empty((n_chans, n_pts), dtype=np.complex64)
    elif x.dtype == np.float64 or x.dtype == np.complex128:
        yy = np.empty((n_chans, n_pts), dtype=np.complex128)

    reg = np.zeros((n_chans, n_taps), dtype=dtype)

    # instead of n_chans here, this could be channel separation
    for i, nn in enumerate(range(0, len(x), n_chans)):
        reg[:, 1:n_taps] = reg[:, 0 : (n_taps - 1)]
        reg[:, 0] = np.conj(np.flipud(x[nn : (nn + n_chans)]))
        for mm in range(n_chans):
            vv[mm] = np.array(reg[mm, :] * hh[mm, :].H)

        yy[:, i] = np.conj(np.fft.fft(vv))

    return yy
```

**Comment by mnicely** [comment]
@awthomp 
@z-ryan1 said `freq_shift` isn't in `scipy.signal`. Did you add that special for someone?
How do you envision testing it?

**Comment by awthomp** [comment]
> @awthomp
> @z-ryan1 said `freq_shift` isn't in `scipy.signal`. Did you add that special for someone?
> How do you envision testing it?

The frequency shift is just a simple elementwise function that's commonly used in baseband processing. I think the best way to test it would be doing the equivalent in numpy, similar to what we're doing with the polyphase channelizer. Luckily, this is really easy, here!

```python
def freq_shift(x, freq, fs):
    """
    Frequency shift signal by freq at fs sample rate
    Parameters
    ----------
    x : array_like, complex valued
        The data to be shifted.
    freq : float
        Shift by this many (Hz)
    fs : float
        Sampling rate of the signal
    domain : string
        freq or time
    """
    x = np.asarray(x)
    return x * np.exp(-1j * 2 * np.pi * freq / fs * np.arange(x.size))
```

**Comment by mnicely** [comment]
> > @awthomp
> > @z-ryan1 said `freq_shift` isn't in `scipy.signal`. Did you add that special for someone?
> > How do you envision testing it?
> 
> The frequency shift is just a simple elementwise function that's commonly used in baseband processing. I think the best way to test it would be doing the equivalent in numpy, similar to what we're doing with the polyphase channelizer. Luckily, this is really easy, here!
> 
> ```python
> def freq_shift(x, freq, fs):
>     """
>     Frequency shift signal by freq at fs sample rate
>     Parameters
>     ----------
>     x : array_like, complex valued
>         The data to be shifted.
>     freq : float
>         Shift by this many (Hz)
>     fs : float
>         Sampling rate of the signal
>     domain : string
>         freq or time
>     """
>     x = np.asarray(x)
>     return x * np.exp(-1j * 2 * np.pi * freq / fs * np.arange(x.size))
> ```

If that's the case, @z-ryan1 I think this is a good to apply what you've learned with Elementwise kernels! In a new PR.

**Comment by mnicely** [comment]
ok to test

**Comment by BradReesWork** [comment]
ok to test

**Comment by BradReesWork** [comment]
add to whitelist

**Review by mnicely — APPROVED** [review]

**Review by awthomp — APPROVED** [review]

**Comment by awthomp** [comment]
Really nice work, @z-ryan1! @mnicely -- LGTM after CI passes!

**Pull request merged**
