### PR TITLE
[PR-REVIEW] Combine tests and benchmarks

### LINKED ISSUE #169: [FEA] Combine test and benchmarks
Currently, we maintain `tests` and `benchmarks` directories.

Tests are used during the CI process and benchmarks are used as a performance check.

Maintaining has lead to a couple issues and increased workload. 

Investigation needs to be performed to determine if these can be combined and a clean manner.

### PR DESCRIPTION
**Pull request by mnicely**
## Info
Recently, I've had to scan CI logs trying to debug some issues and notices all the **SKIPPED** benchmark runs that were showing up in the logs. 

In the process to trying to hide the SKIPPED runs, I discovered that I could combine tests and benchmarks. This is even more appealing because it allows us to no longer maintain both folders and tests (double the code)

### How it currently works...
Currently, in `setup.cfg` there is a flag **--benchmark-skip** which skips all test with expression _bench__ or _Bench_.
So by default, all benchmarks are skipped, which is what we want during CI.

Then when a developer wants to benchmark functions, the flag **--benchmark-only** needs to be passed. In this case, all functions with expression _test__ or _Test_ are SKIPPED.

### Proposal
This PR proposals the following:
1. All benchmarks be moved to _test__ and _Test_.
- Follow traditional naming scheme
2. Replace **--benchmark-skip** with **--benchmark-disable**
- This disables benchmark runs and executing only one run to check assert (Just like traditional pytest)
3. Add **@pytest.mark.cpu** to and CPU (SciPy) functions
- Marker allowing pytest to skip CPU functions during CI
4. Add *-m "not cpu" to CI/GPU `build.sh`
- Flag allow pytest to skip CPU functions during CI

@rlratzel Thought you might find this useful because I recall you looking into pytest-benchmark awhile back.

### Issues
Fixes #169

### CODE REVIEW

**Comment by GPUtester** [comment]
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

**Comment by GPUtester** [comment]
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

**Comment by rlratzel** [comment]
Thanks for including me, @mnicely .  You might also be interested in a pytest plugin I wrote (@ajschmidt8 is now the current maintainer) that adds GPU metrics to the benchmark output.  You simply install the plugin (`conda install -c rapidsai rapids-pytest-benchmark`) and replace the `benchmark` fixture with `gpubenchmark`.  Like `benchmark`, you can also add `gpubenchmark` as a fixture to a standard unit test, or just run benchmarks side-by-side with tests like you're doing here to get perf. results without adding the overhead of a separate run, folder, etc.  More info [here](https://github.com/rapidsai/benchmark/blob/main/README.md) and [here](https://github.com/rapidsai/benchmark/blob/main/rapids_pytest_benchmark/README.md)

**Comment by mnicely** [comment]
Now `rapids-pytest-benchmark` is integrated!

I've also added @rlratzel fallback code.

```python
import pytest_benchmark

try:
    from rapids_pytest_benchmark import setFixtureParamNames
except ImportError:
    print(
        "\n\nWARNING: rapids_pytest_benchmark is not installed, "
        "falling back to pytest_benchmark fixtures.\n"
    )

    # if rapids_pytest_benchmark is not available, just perfrom time-only
    # benchmarking and replace the util functions with nops
    gpubenchmark = pytest_benchmark.plugin.benchmark

    def setFixtureParamNames(*args, **kwargs):
        pass
```

If you want to benchmark cuSignal GPU function like previously, you want to run benchmarks you need to ensure you add `--benchmark-gpu-disable`.

This will skip `rapids-pytest-benchmark` memory checks, speeding up run time.

**Pull request merged**
