### PR TITLE
[WIP] Implementation of `sosfilt` as an alternative to `lfilter`

### PR DESCRIPTION
**Pull request by awthomp**
Scaffolding code for our `sosfilt` implementation. A few things here:
* `sosfilt` placed in `filtering/filtering.py`
* added `filter_design_utils.py` in `filter_design` for sos structure validation
* Added `sosfilt` Python code (to be moved to Numba/CuPy CUDA) in `filtering/_sosfilt_cuda.py`
* Updated documentation for sosfilt. @mnicely -- the example listed in the doc should serve as a good test case. I've pasted it below, too:

```python
from scipy import signal
import cusignal
import cupy as cp

# Generate filter on CPU with Scipy.Signal then move to GPU
sos = signal.ellip(13, 0.009, 80, 0.05, output='sos')
sos = cp.asarray(sos)

x = cp.random.randn(100_000_000)
y = cusignal.sosfilt(sos, x)
```

To-do:

- [ ] Create CUDA kernel for sosfilt with no initial conditions (e.g. Zi = None) - @mnicely 
- [ ] Build out `sos` filter output representation (e.g. cusignal equivalent of `signal.ellip(output='sos')` - @awthomp 
- [ ] Performance evaluation w.r.t. SciPy Signal
- [ ] Confirm I have a sensible code structure
- [ ] Eventually build out support for initial conditions (e.g. Zi is not None).

I'm going to target this for 0.15 but think the algorithm is straighforward enough to get into 0.14.

closes https://github.com/rapidsai/cusignal/issues/52

### CODE REVIEW

**Comment by mnicely** [comment]
## Benchmark
It looks like the Numba version excels when the number of signals or sections are large. 
For the smallest scenaro (1, 2^15, 32) --- CPU is 5x faster
For the largest scenario (10, 2^20, 512) --- GPU is 10 faster

Notice that GPU timings are grouped by quantity of sections. This is because 1 single is launched per block. One my RTX Titan there are 72 SM. It takes an order of 64 (32 threads per block) and 32 blocks * 72 SM = 2304 signals to saturate the GPU. 

Order would need to be 128 on anything but CC 7.5

```bash
--------------------------------------------------------------------------------------------- benchmark 'SOSFilt': 60 tests ---------------------------------------------------------------------------------------------
Name (time in ms)                                 Min                   Max                  Mean             StdDev                Median                IQR            Outliers       OPS            Rounds  Iterations
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
bench_sosfilt_cpu[1-32768-32]                  1.3025 (1.0)          1.7219 (1.0)          1.3410 (1.0)       0.0401 (2.74)         1.3283 (1.0)       0.0121 (3.48)       64;123  745.6988 (1.0)         555           1
bench_sosfilt_cpu[2-32768-32]                  2.5729 (1.98)        50.9488 (29.59)        2.9430 (2.19)      2.6673 (182.71)       2.6252 (1.98)      0.0930 (26.86)        7;54  339.7861 (0.46)        383           1
bench_sosfilt_cpu[1-32768-64]                  2.8328 (2.17)         2.9763 (1.73)         2.8560 (2.13)      0.0146 (1.0)          2.8576 (2.15)      0.0179 (5.16)         88;2  350.1444 (0.47)        351           1
bench_sosfilt_cpu[2-32768-64]                  5.6344 (4.33)         6.1408 (3.57)         5.6944 (4.25)      0.0499 (3.42)         5.6831 (4.28)      0.0279 (8.05)        20;12  175.6106 (0.24)        177           1
bench_sosfilt_cpu[1-32768-128]                 5.8949 (4.53)         6.7156 (3.90)         5.9646 (4.45)      0.1490 (10.21)        5.9179 (4.46)      0.0217 (6.27)        17;29  167.6571 (0.22)        168           1
bench_sosfilt_gpu[True-1-32768-32]             8.7844 (6.74)        15.2799 (8.87)         8.9926 (6.71)      0.8837 (60.53)        8.7904 (6.62)      0.0047 (1.37)          3;9  111.2020 (0.15)         83           1
bench_sosfilt_gpu[True-2-32768-32]             8.7946 (6.75)        12.6503 (7.35)         8.8422 (6.59)      0.3607 (24.70)        8.8040 (6.63)      0.0051 (1.48)         1;10  113.0936 (0.15)        114           1
bench_sosfilt_gpu[True-10-32768-32]            8.8675 (6.81)         9.7029 (5.63)         8.8881 (6.63)      0.0955 (6.54)         8.8745 (6.68)      0.0060 (1.73)          2;9  112.5104 (0.15)        113           1
bench_sosfilt_gpu[True-1-32768-64]             9.0037 (6.91)         9.4608 (5.49)         9.0201 (6.73)      0.0576 (3.95)         9.0089 (6.78)      0.0042 (1.21)         4;10  110.8631 (0.15)        110           1
bench_sosfilt_gpu[True-2-32768-64]             9.0179 (6.92)         9.5620 (5.55)         9.0624 (6.76)      0.0962 (6.59)         9.0264 (6.80)      0.0123 (3.54)        14;18  110.3464 (0.15)        109           1
bench_sosfilt_gpu[True-10-32768-64]            9.0839 (6.97)         9.4118 (5.47)         9.1060 (6.79)      0.0607 (4.16)         9.0907 (6.84)      0.0059 (1.70)         6;13  109.8178 (0.15)        109           1
bench_sosfilt_gpu[True-1-32768-128]            9.3159 (7.15)        13.2531 (7.70)         9.5308 (7.11)      0.4844 (33.18)        9.3339 (7.03)      0.2236 (64.58)        5;12  104.9232 (0.14)        108           1
bench_sosfilt_gpu[True-2-32768-128]            9.3402 (7.17)        13.5152 (7.85)         9.5657 (7.13)      0.5419 (37.12)        9.3546 (7.04)      0.2306 (66.60)        6;16  104.5397 (0.14)        108           1
bench_sosfilt_gpu[True-10-32768-128]           9.4098 (7.22)        19.3030 (11.21)        9.7041 (7.24)      1.0918 (74.79)        9.4217 (7.09)      0.2253 (65.08)        4;11  103.0492 (0.14)        107           1
bench_sosfilt_gpu[True-1-32768-256]           11.4388 (8.78)        11.5585 (6.71)        11.4476 (8.54)      0.0153 (1.05)        11.4447 (8.62)      0.0054 (1.56)          4;6   87.3549 (0.12)         88           1
bench_sosfilt_gpu[True-2-32768-256]           11.4585 (8.80)        11.6244 (6.75)        11.4697 (8.55)      0.0186 (1.27)        11.4664 (8.63)      0.0050 (1.45)         5;10   87.1863 (0.12)         88           1
bench_sosfilt_gpu[True-10-32768-256]          11.5442 (8.86)        11.6761 (6.78)        11.5525 (8.61)      0.0160 (1.09)        11.5498 (8.70)      0.0035 (1.0)           2;7   86.5611 (0.12)         87           1
bench_sosfilt_cpu[2-32768-128]                11.7958 (9.06)        31.1629 (18.10)       12.6493 (9.43)      3.2251 (220.92)      11.8150 (8.89)      0.2149 (62.06)         4;9   79.0555 (0.11)         85           1
bench_sosfilt_cpu[1-32768-256]                12.1128 (9.30)        28.6142 (16.62)       12.8602 (9.59)      2.5222 (172.77)      12.1334 (9.13)      0.1318 (38.07)        7;15   77.7594 (0.10)         83           1
bench_sosfilt_cpu[10-32768-32]                12.7478 (9.79)        15.0472 (8.74)        13.1349 (9.79)      0.3688 (25.26)       13.0117 (9.80)      0.1702 (49.17)       10;11   76.1329 (0.10)         79           1
bench_sosfilt_gpu[True-1-32768-512]           19.6615 (15.10)       19.8287 (11.52)       19.6704 (14.67)     0.0232 (1.59)        19.6658 (14.81)     0.0052 (1.50)          1;3   50.8377 (0.07)         51           1
bench_sosfilt_gpu[True-2-32768-512]           19.6735 (15.10)       19.9167 (11.57)       19.6939 (14.69)     0.0481 (3.30)        19.6801 (14.82)     0.0050 (1.43)          4;5   50.7773 (0.07)         51           1
bench_sosfilt_gpu[True-10-32768-512]          19.8249 (15.22)       20.0019 (11.62)       19.8414 (14.80)     0.0337 (2.31)        19.8326 (14.93)     0.0076 (2.19)          2;7   50.3998 (0.07)         51           1
bench_sosfilt_cpu[2-32768-256]                24.2202 (18.60)       41.8580 (24.31)       25.2485 (18.83)     2.9752 (203.80)      24.2900 (18.29)     0.4748 (137.11)        4;5   39.6063 (0.05)         42           1
bench_sosfilt_cpu[1-32768-512]                24.3683 (18.71)       48.7258 (28.30)       25.7057 (19.17)     4.7092 (322.58)      24.3839 (18.36)     0.0257 (7.43)          3;9   38.9019 (0.05)         42           1
bench_sosfilt_cpu[10-32768-64]                28.1574 (21.62)      109.5310 (63.61)       31.5416 (23.52)    13.6765 (936.84)      28.4077 (21.39)     0.6498 (187.67)        1;5   31.7042 (0.04)         36           1
bench_sosfilt_cpu[1-1048576-32]               41.1920 (31.63)      104.8606 (60.90)       44.6966 (33.33)    12.9083 (884.22)      41.5117 (31.25)     0.2606 (75.26)         1;4   22.3731 (0.03)         25           1
bench_sosfilt_cpu[2-32768-512]                48.7251 (37.41)       89.1790 (51.79)       50.9903 (38.02)     8.1821 (560.47)      48.7839 (36.73)     0.5571 (160.89)        1;4   19.6116 (0.03)         25           1
bench_sosfilt_cpu[10-32768-128]               58.8414 (45.18)       59.3424 (34.46)       58.9799 (43.98)     0.1027 (7.04)        58.9695 (44.40)     0.1130 (32.62)         4;1   16.9549 (0.02)         25           1
bench_sosfilt_cpu[2-1048576-32]               82.6958 (63.49)      160.3036 (93.09)       86.9750 (64.86)    15.3242 (>1000.0)     83.6806 (63.00)     0.6405 (184.98)        1;5   11.4976 (0.02)         25           1
bench_sosfilt_cpu[1-1048576-64]               90.7498 (69.68)      162.6423 (94.45)       94.3274 (70.34)    14.3112 (980.31)      90.9063 (68.44)     0.1941 (56.05)         1;5   10.6014 (0.01)         25           1
bench_sosfilt_cpu[10-32768-256]              121.1387 (93.01)      185.3275 (107.63)     124.2815 (92.68)    12.7486 (873.28)     121.3687 (91.37)     0.6109 (176.43)        1;5    8.0463 (0.01)         25           1
bench_sosfilt_cpu[2-1048576-64]              180.9901 (138.96)     267.4514 (155.32)     188.2680 (140.39)   20.3153 (>1000.0)    182.4610 (137.37)    2.0165 (582.38)        2;2    5.3116 (0.01)         25           1
bench_sosfilt_cpu[1-1048576-128]             189.5853 (145.56)     283.5120 (164.65)     198.3071 (147.88)   21.4234 (>1000.0)    190.5149 (143.43)    3.4383 (992.99)        2;4    5.0427 (0.01)         25           1
bench_sosfilt_cpu[10-32768-512]              243.7452 (187.14)     314.4197 (182.60)     251.8131 (187.78)   19.6145 (>1000.0)    244.0253 (183.72)    3.6762 (>1000.0)       3;3    3.9712 (0.01)         25           1
bench_sosfilt_gpu[True-1-1048576-32]         284.9224 (218.76)     295.5722 (171.65)     285.5370 (212.92)    2.1040 (144.12)     285.0528 (214.60)    0.1174 (33.89)         1;5    3.5022 (0.00)         25           1
bench_sosfilt_gpu[True-2-1048576-32]         284.9807 (218.80)     288.1245 (167.33)     286.1687 (213.40)    1.1248 (77.05)      285.7653 (215.14)    2.1379 (617.44)        7;0    3.4944 (0.00)         25           1
bench_sosfilt_gpu[True-10-1048576-32]        287.1755 (220.49)     289.4426 (168.09)     287.4308 (214.34)    0.4465 (30.59)      287.3055 (216.30)    0.1604 (46.33)         1;2    3.4791 (0.00)         25           1
bench_sosfilt_gpu[True-1-1048576-64]         291.7119 (223.97)     293.8735 (170.66)     292.1003 (217.82)    0.6168 (42.25)      291.8593 (219.73)    0.1130 (32.64)         3;5    3.4235 (0.00)         25           1
bench_sosfilt_gpu[True-2-1048576-64]         293.9356 (225.68)     300.6892 (174.62)     294.3766 (219.52)    1.3433 (92.02)      294.0655 (221.39)    0.1337 (38.62)         1;4    3.3970 (0.00)         25           1
bench_sosfilt_gpu[True-10-1048576-64]        293.9797 (225.71)     300.3571 (174.43)     294.6243 (219.70)    1.6460 (112.75)     294.1148 (221.43)    0.1428 (41.25)         2;4    3.3942 (0.00)         25           1
bench_sosfilt_gpu[True-1-1048576-128]        299.5703 (230.00)     300.7107 (174.64)     299.8243 (223.58)    0.2423 (16.59)      299.7155 (225.64)    0.2520 (72.79)         3;1    3.3353 (0.00)         25           1
bench_sosfilt_gpu[True-2-1048576-128]        301.9373 (231.82)     308.2813 (179.03)     302.4312 (225.52)    1.2481 (85.49)      302.0628 (227.41)    0.3409 (98.44)         1;2    3.3065 (0.00)         25           1
bench_sosfilt_gpu[True-10-1048576-128]       302.0221 (231.88)     308.0782 (178.91)     302.6306 (225.67)    1.1883 (81.40)      302.3763 (227.64)    0.1783 (51.51)         2;3    3.3044 (0.00)         25           1
bench_sosfilt_gpu[True-1-1048576-256]        361.0070 (277.17)     371.9183 (215.99)     361.5397 (269.60)    2.1648 (148.29)     361.0961 (271.85)    0.0658 (19.00)         1;2    2.7659 (0.00)         25           1
bench_sosfilt_gpu[True-2-1048576-256]        364.0221 (279.49)     378.3462 (219.72)     364.7491 (271.99)    2.8376 (194.38)     364.1484 (274.15)    0.0838 (24.21)         1;4    2.7416 (0.00)         25           1
bench_sosfilt_gpu[True-10-1048576-256]       364.0759 (279.53)     365.6579 (212.35)     364.2535 (271.62)    0.3158 (21.63)      364.1963 (274.19)    0.0779 (22.49)         2;2    2.7453 (0.00)         25           1
bench_sosfilt_cpu[2-1048576-128]             376.4316 (289.01)     460.4778 (267.42)     391.4291 (291.89)   26.9649 (>1000.0)    377.3417 (284.08)    8.6431 (>1000.0)       5;6    2.5547 (0.00)         25           1
bench_sosfilt_cpu[1-1048576-256]             388.9246 (298.61)     492.6661 (286.11)     405.3332 (302.26)   32.0007 (>1000.0)    390.5037 (293.99)    2.9230 (844.19)        5;5    2.4671 (0.00)         25           1
bench_sosfilt_cpu[10-1048576-32]             419.9300 (322.41)     514.6709 (298.89)     437.1384 (325.97)   29.7104 (>1000.0)    421.5810 (317.39)    9.0118 (>1000.0)       5;5    2.2876 (0.00)         25           1
bench_sosfilt_gpu[True-1-1048576-512]        593.7039 (455.83)     594.3337 (345.15)     593.8352 (442.82)    0.1775 (12.16)      593.7746 (447.03)    0.0468 (13.52)         3;3    1.6840 (0.00)         25           1
bench_sosfilt_gpu[True-2-1048576-512]        598.3827 (459.42)     600.7376 (348.87)     598.6737 (446.43)    0.6060 (41.51)      598.4742 (450.56)    0.0504 (14.57)         2;4    1.6704 (0.00)         25           1
bench_sosfilt_gpu[True-10-1048576-512]       598.4018 (459.44)     603.9728 (350.75)     601.3986 (448.46)    2.3611 (161.74)     603.2123 (454.13)    4.7642 (>1000.0)      10;0    1.6628 (0.00)         25           1
bench_sosfilt_cpu[2-1048576-256]             773.9583 (594.22)     870.6651 (505.63)     804.8599 (600.18)   37.2791 (>1000.0)    776.7888 (584.81)   70.6851 (>1000.0)       9;0    1.2425 (0.00)         25           1
bench_sosfilt_cpu[1-1048576-512]             779.7424 (598.67)     878.2046 (510.01)     814.1396 (607.10)   40.5453 (>1000.0)    785.0156 (591.00)   78.1414 (>1000.0)       8;0    1.2283 (0.00)         25           1
bench_sosfilt_cpu[10-1048576-64]             910.9197 (699.38)   1,025.5475 (595.58)     953.6615 (711.14)   39.6086 (>1000.0)    944.6553 (711.19)   71.3349 (>1000.0)      10;0    1.0486 (0.00)         25           1
bench_sosfilt_cpu[2-1048576-512]           1,563.0005 (>1000.0)  1,668.2269 (968.81)   1,617.7672 (>1000.0)  28.0736 (>1000.0)  1,624.5981 (>1000.0)  27.8852 (>1000.0)       7;2    0.6181 (0.00)         25           1
bench_sosfilt_cpu[10-1048576-128]          1,930.8164 (>1000.0)  1,992.2240 (>1000.0)  1,960.5759 (>1000.0)  12.4683 (854.08)   1,959.9346 (>1000.0)  16.1785 (>1000.0)       7;1    0.5101 (0.00)         25           1
bench_sosfilt_cpu[10-1048576-256]          3,981.3146 (>1000.0)  4,065.8656 (>1000.0)  4,023.6657 (>1000.0)  19.3833 (>1000.0)  4,021.3042 (>1000.0)  23.3533 (>1000.0)       7;0    0.2485 (0.00)         25           1
bench_sosfilt_cpu[10-1048576-512]          8,051.1417 (>1000.0)  8,184.9009 (>1000.0)  8,099.7664 (>1000.0)  32.0515 (>1000.0)  8,092.7473 (>1000.0)  28.6558 (>1000.0)       7;2    0.1235 (0.00)         25           1
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
```

**Comment by mnicely** [comment]
## Updated benchmark
only gpu (includes float32)
```bash
----------------------------------------------------------------------------------------- benchmark 'SOSFilt': 60 tests ------------------------------------------------------------------------------------------
Name (time in ms)                                  Min                 Max                Mean            StdDev              Median               IQR            Outliers       OPS            Rounds  Iterations
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
bench_sosfilt_gpu[float32-1-32768-32]           2.8416 (1.0)        4.1028 (1.31)       2.9604 (1.03)     0.3331 (38.43)      2.8480 (1.0)      0.0079 (2.06)        22;42  337.7964 (0.97)        250           1
bench_sosfilt_gpu[float32-2-32768-32]           2.8507 (1.00)       3.1504 (1.00)       2.8684 (1.0)      0.0403 (4.65)       2.8563 (1.00)     0.0073 (1.91)        28;45  348.6271 (1.0)         348           1
bench_sosfilt_gpu[float32-10-32768-32]          2.8755 (1.01)      11.2327 (3.58)       3.0079 (1.05)     0.6009 (69.32)      2.8837 (1.01)     0.0683 (17.82)        7;45  332.4573 (0.95)        348           1
bench_sosfilt_gpu[float32-1-32768-64]           2.9505 (1.04)      35.4576 (11.29)      3.1496 (1.10)     1.9773 (228.12)     2.9547 (1.04)     0.0042 (1.10)         3;39  317.5013 (0.91)        338           1
bench_sosfilt_gpu[float32-2-32768-64]           2.9580 (1.04)      11.8467 (3.77)       3.1124 (1.09)     0.6669 (76.94)      2.9691 (1.04)     0.0993 (25.92)        8;38  321.2998 (0.92)        338           1
bench_sosfilt_gpu[float32-10-32768-64]          2.9854 (1.05)       3.3724 (1.07)       3.0245 (1.05)     0.0623 (7.19)       2.9974 (1.05)     0.0379 (9.90)        40;40  330.6307 (0.95)        334           1
bench_sosfilt_gpu[float32-1-32768-128]          3.0261 (1.06)       3.2669 (1.04)       3.0473 (1.06)     0.0475 (5.48)       3.0307 (1.06)     0.0061 (1.59)        35;40  328.1568 (0.94)        328           1
bench_sosfilt_gpu[float32-2-32768-128]          3.0357 (1.07)       3.1393 (1.0)        3.0424 (1.06)     0.0087 (1.0)        3.0404 (1.07)     0.0047 (1.23)        18;18  328.6843 (0.94)        329           1
bench_sosfilt_gpu[float32-10-32768-128]         3.0626 (1.08)       7.3575 (2.34)       3.1927 (1.11)     0.4249 (49.02)      3.0736 (1.08)     0.1012 (26.40)       11;39  313.2194 (0.90)        326           1
bench_sosfilt_gpu[float32-1-32768-256]          3.6320 (1.28)      19.2845 (6.14)       3.7595 (1.31)     0.9488 (109.46)     3.6386 (1.28)     0.0581 (15.16)        1;46  265.9923 (0.76)        275           1
bench_sosfilt_gpu[float32-2-32768-256]          3.6425 (1.28)       5.5949 (1.78)       3.7474 (1.31)     0.2225 (25.67)      3.6514 (1.28)     0.1302 (33.99)       32;32  266.8499 (0.77)        275           1
bench_sosfilt_gpu[float32-10-32768-256]         3.6748 (1.29)       3.8534 (1.23)       3.6834 (1.28)     0.0193 (2.23)       3.6780 (1.29)     0.0038 (1.0)         17;34  271.4892 (0.78)        272           1
bench_sosfilt_gpu[float32-1-32768-512]          5.3109 (1.87)       5.4343 (1.73)       5.3417 (1.86)     0.0144 (1.66)       5.3439 (1.88)     0.0067 (1.74)        34;33  187.2046 (0.54)        189           1
bench_sosfilt_gpu[float32-2-32768-512]          5.3231 (1.87)       5.4644 (1.74)       5.3580 (1.87)     0.0152 (1.75)       5.3563 (1.88)     0.0059 (1.55)        20;27  186.6377 (0.54)        187           1
bench_sosfilt_gpu[float32-10-32768-512]         5.4048 (1.90)       5.7362 (1.83)       5.4922 (1.91)     0.0795 (9.17)       5.4670 (1.92)     0.1177 (30.73)        37;1  182.0760 (0.52)        175           1
bench_sosfilt_gpu[float64-1-32768-32]           8.3013 (2.92)      22.1742 (7.06)       8.5826 (2.99)     1.4772 (170.42)     8.3155 (2.92)     0.1815 (47.37)         1;6  116.5143 (0.33)         88           1
bench_sosfilt_gpu[float64-2-32768-32]           8.3770 (2.95)       8.6028 (2.74)       8.3963 (2.93)     0.0349 (4.03)       8.3848 (2.94)     0.0095 (2.47)        13;20  119.1007 (0.34)        120           1
bench_sosfilt_gpu[float64-10-32768-32]          8.3825 (2.95)       8.6836 (2.77)       8.4350 (2.94)     0.0626 (7.23)       8.4078 (2.95)     0.0498 (12.99)       19;14  118.5530 (0.34)        114           1
bench_sosfilt_gpu[float64-1-32768-64]           8.5328 (3.00)       8.8046 (2.80)       8.5527 (2.98)     0.0510 (5.89)       8.5376 (3.00)     0.0067 (1.75)         8;13  116.9219 (0.34)        118           1
bench_sosfilt_gpu[float64-2-32768-64]           8.6179 (3.03)      11.6287 (3.70)       8.7486 (3.05)     0.3360 (38.77)      8.6435 (3.03)     0.1368 (35.71)        5;11  114.3043 (0.33)        117           1
bench_sosfilt_gpu[float64-10-32768-64]          8.6211 (3.03)      28.2934 (9.01)       8.8925 (3.10)     1.8229 (210.30)     8.6471 (3.04)     0.1550 (40.45)         1;8  112.4546 (0.32)        116           1
bench_sosfilt_gpu[float64-1-32768-128]          8.8753 (3.12)       9.6054 (3.06)       8.9770 (3.13)     0.1550 (17.88)      8.8875 (3.12)     0.1482 (38.68)       14;11  111.3957 (0.32)        113           1
bench_sosfilt_gpu[float64-10-32768-128]         8.9631 (3.15)       9.1829 (2.93)       8.9980 (3.14)     0.0383 (4.42)       8.9851 (3.15)     0.0271 (7.07)        14;14  111.1362 (0.32)        112           1
bench_sosfilt_gpu[float64-2-32768-128]          8.9642 (3.15)      14.2858 (4.55)       9.1637 (3.19)     0.6687 (77.14)      8.9906 (3.16)     0.1451 (37.87)        4;11  109.1263 (0.31)        112           1
bench_sosfilt_gpu[float64-1-32768-256]         10.7325 (3.78)      13.6413 (4.35)      10.8638 (3.79)     0.3373 (38.92)     10.7416 (3.77)     0.1441 (37.59)         4;9   92.0487 (0.26)         94           1
bench_sosfilt_gpu[float64-2-32768-256]         10.8292 (3.81)      10.9830 (3.50)      10.8556 (3.78)     0.0371 (4.28)      10.8385 (3.81)     0.0246 (6.42)        12;11   92.1182 (0.26)         93           1
bench_sosfilt_gpu[float64-10-32768-256]        10.8355 (3.81)      14.9259 (4.75)      11.0442 (3.85)     0.4876 (56.26)     10.9424 (3.84)     0.2068 (53.96)         3;5   90.5449 (0.26)         93           1
bench_sosfilt_gpu[float64-1-32768-512]         18.1307 (6.38)      18.2928 (5.83)      18.1676 (6.33)     0.0241 (2.78)      18.1717 (6.38)     0.0133 (3.47)        14;13   55.0431 (0.16)         56           1
bench_sosfilt_gpu[float64-2-32768-512]         18.3357 (6.45)      19.0039 (6.05)      18.4205 (6.42)     0.1400 (16.15)     18.3490 (6.44)     0.1604 (41.85)         4;4   54.2874 (0.16)         55           1
bench_sosfilt_gpu[float64-10-32768-512]        18.3602 (6.46)      20.1273 (6.41)      18.5579 (6.47)     0.3374 (38.92)     18.4433 (6.48)     0.1919 (50.09)         5;7   53.8854 (0.15)         55           1
bench_sosfilt_gpu[float32-1-1048576-32]        89.6433 (31.55)     99.1505 (31.58)     90.1071 (31.41)    1.8874 (217.75)    89.6800 (31.49)    0.0986 (25.74)         1;5   11.0979 (0.03)         25           1
bench_sosfilt_gpu[float32-1-1048576-64]        92.7990 (32.66)    109.3318 (34.83)     93.6108 (32.64)    3.2791 (378.31)    92.8804 (32.61)    0.1856 (48.44)         1;2   10.6825 (0.03)         25           1
bench_sosfilt_gpu[float32-1-1048576-128]       94.2978 (33.18)     94.6819 (30.16)     94.3996 (32.91)    0.0985 (11.36)     94.3756 (33.14)    0.0757 (19.76)         5;3   10.5933 (0.03)         25           1
bench_sosfilt_gpu[float32-2-1048576-32]        94.6203 (33.30)     99.8301 (31.80)     94.9575 (33.10)    1.0204 (117.72)    94.7175 (33.26)    0.0576 (15.02)         1;5   10.5310 (0.03)         25           1
bench_sosfilt_gpu[float32-10-1048576-32]       95.4135 (33.58)    105.3328 (33.55)     95.9354 (33.45)    1.9810 (228.55)    95.4504 (33.51)    0.0886 (23.13)         1;4   10.4237 (0.03)         25           1
bench_sosfilt_gpu[float32-2-1048576-64]        97.8783 (34.44)     98.0697 (31.24)     97.9219 (34.14)    0.0527 (6.09)      97.9039 (34.38)    0.0157 (4.11)          3;4   10.2122 (0.03)         25           1
bench_sosfilt_gpu[float32-10-1048576-64]       98.6367 (34.71)    104.3681 (33.25)     98.9578 (34.50)    1.1281 (130.15)    98.7305 (34.67)    0.0177 (4.61)          1;5   10.1053 (0.03)         25           1
bench_sosfilt_gpu[float32-2-1048576-128]       99.9923 (35.19)    100.5259 (32.02)    100.1228 (34.91)    0.1448 (16.70)    100.0959 (35.15)    0.0864 (22.55)         4;4    9.9877 (0.03)         25           1
bench_sosfilt_gpu[float32-10-1048576-128]     100.1871 (35.26)    106.1095 (33.80)    101.0758 (35.24)    1.8257 (210.63)   100.2164 (35.19)    0.7646 (199.53)        3;3    9.8936 (0.03)         25           1
bench_sosfilt_gpu[float32-1-1048576-256]      109.9500 (38.69)    114.6041 (36.51)    110.4037 (38.49)    1.0294 (118.75)   110.0698 (38.65)    0.1317 (34.37)         2;3    9.0577 (0.03)         25           1
bench_sosfilt_gpu[float32-2-1048576-256]      116.0338 (40.83)    117.6264 (37.47)    116.1882 (40.51)    0.3143 (36.26)    116.1006 (40.77)    0.0238 (6.20)          1;7    8.6067 (0.02)         25           1
bench_sosfilt_gpu[float32-10-1048576-256]     116.1107 (40.86)    116.4186 (37.08)    116.1673 (40.50)    0.0781 (9.01)     116.1341 (40.78)    0.0772 (20.14)         2;2    8.6083 (0.02)         25           1
bench_sosfilt_gpu[float32-1-1048576-512]      150.2657 (52.88)    153.0802 (48.76)    151.0665 (52.67)    0.6104 (70.42)    151.2611 (53.11)    0.8666 (226.16)        7;1    6.6196 (0.02)         25           1
bench_sosfilt_gpu[float32-2-1048576-512]      156.3235 (55.01)    162.7996 (51.86)    157.4173 (54.88)    1.1829 (136.47)   157.3205 (55.24)    0.2107 (54.97)         1;5    6.3525 (0.02)         25           1
bench_sosfilt_gpu[float32-10-1048576-512]     157.3990 (55.39)    176.5259 (56.23)    158.3205 (55.19)    3.7937 (437.67)   157.5381 (55.32)    0.1001 (26.12)         1;2    6.3163 (0.02)         25           1
bench_sosfilt_gpu[float64-1-1048576-32]       277.6603 (97.71)    277.9342 (88.53)    277.7266 (96.82)    0.0653 (7.54)     277.7136 (97.51)    0.0241 (6.28)          3;3    3.6007 (0.01)         25           1
bench_sosfilt_gpu[float64-2-1048576-32]       279.6937 (98.43)    279.9145 (89.16)    279.7409 (97.53)    0.0473 (5.45)     279.7274 (98.22)    0.0112 (2.93)          2;7    3.5747 (0.01)         25           1
bench_sosfilt_gpu[float64-10-1048576-32]      279.9472 (98.52)    280.1757 (89.25)    280.0034 (97.62)    0.0633 (7.30)     279.9781 (98.31)    0.0446 (11.65)         3;3    3.5714 (0.01)         25           1
bench_sosfilt_gpu[float64-1-1048576-64]       284.9650 (100.28)   285.1407 (90.83)    285.0252 (99.37)    0.0351 (4.05)     285.0228 (100.08)   0.0256 (6.69)          6;4    3.5085 (0.01)         25           1
bench_sosfilt_gpu[float64-2-1048576-64]       287.0254 (101.01)   287.1787 (91.48)    287.1016 (100.09)   0.0325 (3.75)     287.1048 (100.81)   0.0193 (5.03)          5;5    3.4831 (0.01)         25           1
bench_sosfilt_gpu[float64-10-1048576-64]      287.3444 (101.12)   291.4762 (92.85)    287.5588 (100.25)   0.8198 (94.58)    287.3626 (100.90)   0.0578 (15.08)         1;4    3.4775 (0.01)         25           1
bench_sosfilt_gpu[float64-1-1048576-128]      294.3871 (103.60)   294.7460 (93.89)    294.4898 (102.67)   0.0973 (11.22)    294.4669 (103.39)   0.0509 (13.30)         4;3    3.3957 (0.01)         25           1
bench_sosfilt_gpu[float64-2-1048576-128]      296.5241 (104.35)   296.8857 (94.57)    296.6200 (103.41)   0.0946 (10.91)    296.5898 (104.14)   0.0317 (8.27)          5;5    3.3713 (0.01)         25           1
bench_sosfilt_gpu[float64-10-1048576-128]     296.7889 (104.44)   299.8693 (95.52)    296.9623 (103.53)   0.6086 (70.21)    296.8237 (104.22)   0.0275 (7.18)          1;4    3.3674 (0.01)         25           1
bench_sosfilt_gpu[float64-1-1048576-256]      346.0003 (121.76)   346.6871 (110.43)   346.0953 (120.66)   0.1375 (15.86)    346.0590 (121.51)   0.0534 (13.94)         1;4    2.8894 (0.01)         25           1
bench_sosfilt_gpu[float64-2-1048576-256]      348.6100 (122.68)   348.8472 (111.12)   348.6571 (121.55)   0.0513 (5.92)     348.6419 (122.42)   0.0269 (7.02)          2;2    2.8681 (0.01)         25           1
bench_sosfilt_gpu[float64-10-1048576-256]     348.8856 (122.78)   349.1146 (111.21)   348.9207 (121.64)   0.0541 (6.24)     348.8997 (122.51)   0.0207 (5.39)          3;4    2.8660 (0.01)         25           1
bench_sosfilt_gpu[float64-1-1048576-512]      563.0888 (198.16)   573.4253 (182.66)   566.3164 (197.43)   2.7846 (321.25)   564.7402 (198.29)   4.3960 (>1000.0)      12;0    1.7658 (0.01)         25           1
bench_sosfilt_gpu[float64-2-1048576-512]      567.5292 (199.72)   569.3492 (181.36)   568.8944 (198.33)   0.6848 (79.01)    569.2183 (199.87)   0.0232 (6.04)          5;7    1.7578 (0.01)         25           1
bench_sosfilt_gpu[float64-10-1048576-512]     567.7787 (199.81)   569.4573 (181.39)   569.3711 (198.50)   0.3319 (38.29)    569.4336 (199.94)   0.0135 (3.54)          1;1    1.7563 (0.01)         25           1
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
```

**Comment by awthomp** [comment]
@mnicely -- How do you feel about merging this into 0.14 with a blurb in the documentation that this is still experimental?

**Comment by mnicely** [comment]
I think that's a good idea.

**Comment by awthomp** [comment]
rerun tests

**Comment by awthomp** [comment]
@mnicely -- I fixed pytests to pass on sosfilt and added a documentation disclaimer. Mind looking over the PR/changes?

@dicta -- do you have any thoughts on going to market here?

**Pull request merged**
