### PR TITLE
[WIP] Implement lfilter method.

### LINKED ISSUE #7: [FEA] Implementation of lfilter.
The `lfilter` function would be really useful for demodulation. For example, FM demodulation (de-emphasis and stereo).

Scipy Signal:
https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.lfilter.html#scipy.signal.lfilter

### PR DESCRIPTION
**Pull request by luigifreitas**
This pull-request implements a GPU accelerated `lfilter` function originally ported from PyTorch. This code aims to address issue #7.

closes #7

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by awthomp** [comment]
ok to test

**Comment by awthomp** [comment]
ok to test

**Comment by awthomp** [comment]
Thanks for the PR, @luigifreitas. @mnicely has forked your request and is currently looking at performance optimizations.

**Comment by mnicely** [comment]
Hi @luigifreitas, thanks for starting the code base. I've been analysing the math and control and have found that PyTorch is not running a the GPU in a traditional sense. 

If you look at my numbers from yesterday, it's not really that fast. The input signal is size 2^16, while **a** and **b** are size 3.

PyTorch (GPU)  |     CuPy calls    |    signal.lfilter
    2.5s                |       3.2s           |        250us

If you look at the code, you'll see that the inputs for **windowed_output_signal** require the **o0** from the previous iteration. This dependency doesn't allow for multiple threads to run independently. 
As an example, thread 5 can't start work because it need the result from thread 4 and so forth.

@awthomp and I believe the best thing to do, for now, is to put the control flow in a single thread. I'll start working on that in a CuPy raw kernel today. The execution will be slower than on a CPU but it will allow users to keep data on the GPU.

**Comment by awthomp** [comment]
And to be clear, I think this is a surprisingly common design bottleneck when analyzing GPU vs CPU implementations for signal processing tasks, in particular. Going to a single CUDA thread, as @mnicely stated, will make lfilter slower than `scipy.signal`, however, a user rarely, if ever, only does lfilter on GPU. Once Matt has polished up some code, we can profile standard end-to-end workflows like resample, decimate, generate filter, apply filter, etc. 

To stress: we believe end-to-end performance will be greater than both CPU performance and a hybrid GPU/CPU implementation.

It's all about keeping data on the GPU, baby!

**Comment by BradReesWork** [comment]
okay to test

**Comment by BradReesWork** [comment]
rerun tests

**Pull request merged**
