### PR TITLE
[REVIEW] cuSignal restructuring

### PR DESCRIPTION
**Pull request by seunghwak**
This PR addresses https://github.com/rapidsai/cusignal/issues/10

- [x] Create the /python directory
- [x] Run flake8 on python files and fix formatting errors and add setup.cfg file specifying flake8 configurations
- [x]  Add build.sh
- [x] Add print_env.sh
- [x] Add MANIFEST.in, versioneer.py, and _version.py.
- [x] Update setup.py to mimic other RAPIDS projects.
- [x] Add license statements
- [x] Avoid using import * in \_\_init\_\_.py files
- [x] Generate documentation to link to the RAPIDS docs (in this PR, just create a template, full documentation update will be addressed in a separate PR)
- [x] Replace \_\_PROJECT\_\_ with cuSignal in template files under .github
- [x] Remove _input_swaps_needed in _signaltools.py (this is a duplicate of the same function defined in signaltools.py)

### CODE REVIEW

**Comment by awthomp** [comment]
Awesome! Thanks for the hard work, @seunghwak. I'll review over the next day. I also requested a review from @BradReesWork as he's more familiar with the RAPIDS standard lib structure than me.

**Comment by awthomp** [comment]
> @awthomp
> 
> https://github.com/rapidsai/cusignal/blob/57ef73ada63f4858d592a039ac2b0df1a8f4c5e1/cusignal/signaltools.py#L197
> 
> 
> https://github.com/rapidsai/cusignal/blob/57ef73ada63f4858d592a039ac2b0df1a8f4c5e1/cusignal/signaltools.py#L212
> 
> It seems like the above lines are out-dated (I guess sigtools & _correlateND are old names), and how should I fix these?
> 
> And could you review this?
> 
> In particular, could you check I'm not deleting something I shouldn't in [2002b69](https://github.com/rapidsai/cusignal/commit/2002b695eacbe9451c663d2a70c84ac8fb3a72e0) and I properly fixed bugs in [78c0257](https://github.com/rapidsai/cusignal/commit/78c025718f1aa173ace95abc5627db2d3c2469bb)

The `sigtools._correlateND` is a holdover from [SciPy Signal](https://github.com/scipy/scipy/blob/master/scipy/signal/signaltools.py#L234). I'm assuming that else statement isn't stressed/reached in the code, so maybe raise a NotImplementedError?

**Comment by awthomp** [comment]
We should also update the [README](https://github.com/rapidsai/cusignal/blob/master/README.md) to reflect new build instructions with `build.sh`, if applicable.

**Comment by seunghwak** [comment]
> We should also update the [README](https://github.com/rapidsai/cusignal/blob/master/README.md) to reflect new build instructions with `build.sh`, if applicable.

Yes, and we also created the /python directory, so I'll review README and update accordingly.

**Comment by seunghwak** [comment]
> The `sigtools._correlateND` is a holdover from [SciPy Signal](https://github.com/scipy/scipy/blob/master/scipy/signal/signaltools.py#L234). I'm assuming that else statement isn't stressed/reached in the code, so maybe raise a NotImplementedError?

https://github.com/rapidsai/cusignal/blob/57ef73ada63f4858d592a039ac2b0df1a8f4c5e1/cusignal/signaltools.py#L177

ValueError is raised so this part of the code is unreachable. I will delete this unreachable code to silence flake8 "F821 undefined name 'sigtools'" for now. We may revive this code when we implement "direct" method in cuSignal.

**Comment by seunghwak** [comment]
@awthomp 

I updated README (https://github.com/rapidsai/cusignal/pull/11/commits/d84507d2312e56f78135b771cddda940d7915581) and could you check I didn't mess up with the windows part? (I don't have a windows system to test and I haven't used windows for professional work for quite long, I skipped the explanation about the build.sh in the windows part as build.sh assumes bash and may not work on windows systems).

**Comment by awthomp** [comment]
@evanmayer -- Do you mind locally grabbing this PR and seeing if the new README instructions work for Windows? @seunghwak, I also don't have a Windows system to test.

Let us know if you need help. Basically, you'll want to run:
`git fetch origin pull/11/head:cusignal_refactor` in your cusignal git directory. This will checkout this PR as a branch called `cusignal_refactor` from which you can check it out and try the new install directions/cusignal setup.

**Comment by evanmayer** [comment]
I can give a shot, yeah. Depending on how involved your build.sh is, I can take a swing at making an equivalent .bat for Windows, but no promises. Windows isn't my platform of choice either.

**Comment by evanmayer** [comment]
@awthomp 
Small install issue here. It seems like the results of the conda cudatoolkit package install process have changed somewhat since the last time I tried this. This time, I got libNVVM not found errors. It looks like an environment setting issue, probably related to [not having $CUDA_HOME set](https://github.com/rapidsai/cudf/issues/1861), but I have no idea why I was able to get by without doing that last time. Was this dependency not being exercised in the tests before, or was my previous install able to locate my CUDA install automatically?

I was able to get all tests passing again [after running](https://stackoverflow.com/a/59449574) `set CUDA_HOME=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1` in my Anaconda prompt, but that seems like a band-aid.

**Comment by awthomp** [comment]
> @awthomp
> Small install issue here. It seems like the results of the conda cudatoolkit package install process have changed somewhat since the last time I tried this. This time, I got libNVVM not found errors. It looks like an environment setting issue, probably related to [not having $CUDA_HOME set](https://github.com/rapidsai/cudf/issues/1861), but I have no idea why I was able to get by without doing that last time. Was this dependency not being exercised in the tests before, or was my previous install able to locate my CUDA install automatically?
> 
> I was able to get all tests passing again [after running](https://stackoverflow.com/a/59449574) `set CUDA_HOME=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1` in my Anaconda prompt, but that seems like a band-aid.

@seunghwak -- Do you or anyone else on the team know how to handle the Windows CUDA environment variable safely within `build.sh`?

**Comment by seunghwak** [comment]
> @seunghwak -- Do you or anyone else on the team know how to handle the Windows CUDA environment variable safely within `build.sh`?

I haven't used CUDA on Windows, but based on googling (https://github.com/numba/numba/pull/4741), it seems like CUDA_PATH (instead of CUDA_HOME) is used in Windows, and this may be a source of confusion.

And I agree that we may not provide a build.sh equivalent for Windows as build.sh is added pretty recently in RAPIDS as a convenience tool and is not required to using RAPIDS.

**Comment by evanmayer** [comment]
Yeah, CUDA_PATH is currently set, but CUDA_HOME is not:

image

@seunghwak, your link helped me diagnose what was going wrong with my install. I can `pytest --pdb` the cusignal unit tests to see which numba install is having problems attempting to get the paths to my CUDA install:
~~~
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> PDB post_mortem (IO-capturing turned off) >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
> f:\anaconda3\lib\site-packages\numba\cuda\cudadrv\nvvm.py(116)__new__()
-> raise NvvmSupportError(errmsg % e)
(Pdb)
~~~
I assumed `get_cuda_home()` is being called from that numba, and it is, after putting in a `set_trace()` and running `pytest`:
~~~
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> PDB set_trace (IO-capturing turned off) >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
> f:\anaconda3\lib\site-packages\numba\cuda\cuda_paths.py(133)get_cuda_home()
-> if cuda_home is None:
(Pdb) c
~~~
and the function looks like:
~~~
def get_cuda_home(*subdirs):
    """Get paths of CUDA_HOME.
    If *subdirs* are the subdirectory name to be appended in the resulting
    path.
    """
    cuda_home = os.environ.get('CUDA_HOME')
    if cuda_home is not None:
        return os.path.join(cuda_home, *subdirs)
~~~
Which does **not** match up with the current state of the numba master branch. It should be fixed due to the PR you linked above! Is my numba install out of date, or do I have the latest stable release, and this patch isn't in it yet? I "patched" the code myself with the latest `get_cuda_home()` long enough to verify that this PR would indeed fix the issue and I could pass the tests.

Even more puzzling, I have a `F:\Anaconda3\pkgs\numba-0.47.0-py38hf9181ef_0\Lib\site-packages\numba\cuda\cuda_paths.py` that **is** up-to-date, but that's not the one that gets used. I've reached the limits of my knowledge of how Anaconda finds this stuff, maybe you or @awthomp can help?

**Comment by awthomp** [comment]
@evanmayer I think we can ultimately create another issue for Windows support and that it shouldn't block the merge of this PR. For Windows users, we still have instructions to correctly install cuSignal without using the `build.sh` script, and I do believe that the Jetson Conda env yml should also work (but haven't tested that!). 

Let's table Windows support here and revisit after merge and a new issue specific to building out Windows support. We can investigate GPU CI/CD here too, if there's enough demand.

**Comment by awthomp** [comment]
@BradReesWork Can you review this PR? I'd like to merge it in the next couple of days, and you're more familiar with the RAPIDS standards than me :).

**Pull request merged**
