### PR TITLE
fix typo in example plotting code

### PR DESCRIPTION
**Pull request by davidbradway**

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by awthomp** [comment]
ok to test

**Comment by davidbradway** [comment]
I'll give that a try, @awthomp . Thanks

**Comment by davidbradway** [comment]
Sorry, I opened that change as a new PR.

**Comment by davidbradway** [comment]
Ok, I think I got it @awthomp. There are other Example code segments that need to be fixed. Should I work on it in this PR, or are you going to get to it later?

**Comment by awthomp** [comment]
Hey @davidbradway -- The PR looks great now! Thanks!

You're more than welcome to fix the broken example code segments. We really value your contributions!!

**Comment by BradReesWork** [comment]
okay to test

**Pull request merged**
