### PR TITLE
[REVIEW] Install dependencies via meta package

### PR DESCRIPTION
**Pull request by raydouglass**
Install dependencies via `rapids-build-env` (which is pre-installed in the containers).

This brings the repo in line with https://docs.rapids.ai/maintainers/depmgmt/

Depends on https://github.com/rapidsai/integration/pull/49

### CODE REVIEW

**Comment by GPUtester** [comment]
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

**Comment by raydouglass** [comment]
> is that going to matter?

Yes, good catch

**Comment by raydouglass** [comment]
rerun tests

**Comment by mike-wendt** [comment]
Failed to build due to error with CI - rerun tests

**Comment by raydouglass** [comment]
rerun tests

**Pull request merged**
