### PR TITLE
[REVIEW] Depreciate single threaded lfilter due to poor performance

### PR DESCRIPTION
**Pull request by awthomp**
We tried, and we were (CURRENTLY!) defeated. We are going to look into FFT alternatives to the linear filter in addition to implementation of sosfilt outlined here: https://github.com/rapidsai/cusignal/issues/52

In our test cases, `cusignal.lfilter` was around 100x slower than `scipy.signal.lfilter` but faster than torchaudio. We figured that end-to-end performance would make up for the 100x deficiency, but we ended up stressing the GPU and significantly throttling the signal processing workload. As a result, we are removing `cusignal.lfilter` from the library.

closes https://github.com/rapidsai/cusignal/issues/90

### CODE REVIEW

**Comment by GPUtester** [comment]
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

**Comment by awthomp** [comment]
rerun tests

**Comment by awthomp** [comment]
@mnicely -- Can you resolve these merge conflicts? They deal with the new benchmark tests, and you're more familiar with that code than me.

**Comment by mnicely** [comment]
@awthomp Can you run flake8 on the merged changes?

**Comment by awthomp** [comment]
> @awthomp Can you run flake8 on the merged changes?

```
./cusignal/benchmark/bench_signaltools.py:180:9: E112 expected an indented block

./cusignal/benchmark/bench_signaltools.py:180:11: E999 IndentationError: expected an indented block

./cusignal/benchmark/bench_signaltools.py:184:5: E303 too many blank lines (2)

./cusignal/benchmark/bench_signaltools.py:207:5: E303 too many blank lines (2)

./cusignal/benchmark/bench_signaltools.py:214:80: E501 line too long (80 > 79 characters)

./cusignal/benchmark/bench_signaltools.py:220:80: E501 line too long (81 > 79 characters)

./cusignal/benchmark/bench_signaltools.py:239:5: E303 too many blank lines (2)

./cusignal/benchmark/bench_signaltools.py:271:5: E303 too many blank lines (2)

./cusignal/benchmark/bench_signaltools.py:278:80: E501 line too long (83 > 79 characters)

./cusignal/benchmark/bench_signaltools.py:282:80: E501 line too long (83 > 79 characters)

./cusignal/benchmark/bench_signaltools.py:293:5: E303 too many blank lines (2)

./cusignal/benchmark/bench_signaltools.py:312:5: E303 too many blank lines (2)

./cusignal/benchmark/bench_signaltools.py:331:5: E303 too many blank lines (2)

./cusignal/benchmark/bench_signaltools.py:350:5: E303 too many blank lines (2)

./cusignal/benchmark/bench_signaltools.py:362:80: E501 line too long (82 > 79 characters)

./cusignal/benchmark/bench_signaltools.py:395:5: E303 too many blank lines (2)

./cusignal/benchmark/bench_signaltools.py:407:80: E501 line too long (82 > 79 characters)
```

**Pull request merged**
