### PR TITLE
[REVIEW] Add git commit to conda package

### PR DESCRIPTION
**Pull request by dillon-cullinan**

### CODE REVIEW

**Comment by GPUtester** [comment]
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

**Comment by BradReesWork** [comment]
rerun tests

**Comment by BradReesWork** [comment]
@dillon-cullinan somewhere the CUDA version is not being set correctly

**Comment by dillon-cullinan** [comment]
rerun tests

**Pull request merged**
