### PR TITLE
[REVIEW] Use PyData Sphinx Theme for Generated Documentation

### LINKED ISSUE #435: [DOC] Update cuSignal documentation to use PyData Sphinx theme
As summarized by @isVoid in https://github.com/rapidsai/cudf/issues/7098 , Python API documentation for RAPIDS projects has historically used the Sphinx Read The Docs theme and served a single large HTML page. This has caused the docs to load slowly as API surfaces have grown and caused users to experience potentially significant latency/delays when searching for functions.

In https://github.com/rapidsai/cudf/pull/8746 , @galipremsagar updated the cuDF documentation to the more responsive PyData Sphinx theme. In https://github.com/rapidsai/cugraph/pull/1793, @BradReesWork made a similar change.

Updating the cuSignal documentation to the PyData Sphinx theme should improve the user experience for our documentation.

### PR DESCRIPTION
**Pull request by cmpadden**
Resolves #435.

- Updated conda environments to install `pydata-sphinx-theme`
- Updated `docs/source/conf.py` to use new theme
- Following the lead of cuDF, added RAPIDS logo and purple styling in `params.css`

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by awthomp** [comment]
ok to test

**Review by ajschmidt8 — APPROVED** [review]
Approving `ops-codeowner` file changes.

**Comment by awthomp** [comment]
@gpucibot merge

**Pull request merged**
