### PR TITLE
[DOC] Update README to optimize CuPy build time on Jetson

### PR DESCRIPTION
**Pull request by awthomp**
Closes https://github.com/rapidsai/cusignal/issues/304

Thanks to @leofang for the hat tip!

### CODE REVIEW

**Comment by znmeb** [comment]
Is there a way to get the `cicc` steps to run concurrently on multiple cores? I'm building a Docker image that has to run on any Jetson, so I would have to get a list of all the possible compute capabilities and run for each one individually It's easier just to let it go the full 47 minutes and have them all.

**Comment by leofang** [comment]
CuPy already builds its modules in parallel since v8. The slowdown is from its two big modules `cupy.cuda.thrust` and `cupy.cuda.cub` that requires `nvcc` (and thus needs the env var) to build the C++ template codes, which is not parallelizable AFAIK. But if we are targeting only one arch (instead of ~10, the default) it should be fairly fast.

**Review by leofang — APPROVED** [review]
With hindsight, in addition to speed up compilation, this would probably also improve performance on Jetson etc, as CuPy does not compile for those targets by default, and very likely it JITs from the PTX code stored in the modules at runtime.

**Review by BradReesWork — APPROVED** [review]

**Comment by BradReesWork** [comment]
rerun tests

**Comment by znmeb** [comment]
> 
> 
> With hindsight, in addition to speed up compilation, this would probably also improve performance on Jetson etc, as CuPy does not compile for those targets by default, and very likely it JITs from the PTX code stored in the modules at runtime.

Can I specify two arch / compute capability combinations at build time? I want to support all of the current development kits, which would be the Nano and the AGX Xavier / Xavier NX.

**Comment by leofang** [comment]
> > With hindsight, in addition to speed up compilation, this would probably also improve performance on Jetson etc, as CuPy does not compile for those targets by default, and very likely it JITs from the PTX code stored in the modules at runtime.
> 
> Can I specify two arch / compute capability combinations at build time? I want to support all of the current development kits, which would be the Nano and the AGX Xavier / Xavier NX.

Good question, @znmeb 🙂 Yes, the CCs can be concatenated with semicolon (`;`), see
https://docs.cupy.dev/en/stable/reference/environment.html

**Comment by znmeb** [comment]
> 
> 
> > > With hindsight, in addition to speed up compilation, this would probably also improve performance on Jetson etc, as CuPy does not compile for those targets by default, and very likely it JITs from the PTX code stored in the modules at runtime.
> > 
> > 
> > Can I specify two arch / compute capability combinations at build time? I want to support all of the current development kits, which would be the Nano and the AGX Xavier / Xavier NX.
> 
> Good question, @znmeb 🙂 Yes, the CCs can be concatenated with semicolon (`;`), see
> https://docs.cupy.dev/en/stable/reference/environment.html

Yes - I just found that link myself. You might want to put it in the README

https://docs.cupy.dev/en/stable/reference/environment.html#for-installation

**Comment by awthomp** [comment]
> You might want to put it in the README

Good idea. Done! Thanks @znmeb and @leofang !

**Pull request merged**
