### PR TITLE
[REVIEW] Implement basic polyphase channelizer

### PR DESCRIPTION
**Pull request by awthomp**
closes https://github.com/rapidsai/cusignal/issues/142

This is a basic implementation of fred harris' polyphase channelizer described in [this paper](http://read.pudn.com/downloads157/ebook/699899/Digital%20Receivers%20and%20Transmitters%20Using%20Polyphase%20Filter%20Banks%20for%20Wireless.pdf). Specifically, this implementation is targeted to the MATLAB code in Appendix I and II, with the attached data focusing on Appendix I.

This implementation assumes that the user has created a 1D filter prior to processing. fred harris uses `remez` in his calculation, but in my testing, I've been using the attached input and filter data. 

[taps.txt](https://github.com/rapidsai/cusignal/files/4932430/taps.txt)
[xx.txt](https://github.com/rapidsai/cusignal/files/4932431/xx.txt)

You can read these into Python via:

```python
import numpy as np
xx = np.genfromtxt('xx.txt', delimiter=',')
h = np.genfromtxt('taps.txt', delimiter=',')
```

Included in this PR is native, non GPU accelerated, Python code and a baseline version with CuPy. We will want to go to a raw CUDA kernel here, as the naive CuPy implementation is actually slower than CPU.

To run the example (on CPU):
```python
import cusignal
y = cusignal.channelize_poly(xx, h, 10, 'F')
```

### CODE REVIEW

**Comment by GPUtester** [comment]
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

**Comment by GPUtester** [comment]
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

**Comment by awthomp** [comment]
rerun tests

**Comment by mnicely** [comment]
@awthomp How do we want to test this? Do we want to remove the CPU version from the cuSignal API but put it in the test suite?

**Comment by mnicely** [comment]
### Sample Code
```python3
import numpy as np
import cupy as cp
import cusignal
from cusignal.test.utils import array_equal
from cupy import prof

np.random.seed(1000)

xx = np.random.rand(2**20)
h = np.random.rand(8192)

loop = 2
chans = 256

xx = xx.astype(np.complex128)
h = h.astype(np.float32)

# Run CPU version
for _ in range(1):
    with prof.time_range("cpu", 0):
        y = cusignal.channelize_poly(xx, h, chans)

# Copy data to gpu
xx = cp.asarray(xx)
h = cp.asarray(h)

# Measure first pass
with prof.time_range("gpu_first_pass", 0):
    gpu_y = cusignal.channelize_poly_gpu(xx, h, chans)
    cp.cuda.runtime.deviceSynchronize()

# Check accuracy
assert array_equal(cp.asnumpy(gpu_y), y)

# Run for performance
for _ in range(loop):
    with prof.time_range("gpu_loop", 0):
        gpu_y = cusignal.channelize_poly_gpu(xx, h, chans)
        cp.cuda.runtime.deviceSynchronize()
```

### To profile
```bash
nsys profile -s none -t cuda,nvtx --stats=true python3 <script>
```

**Comment by mnicely** [comment]
> LGTM
> 
> Wish there was a better way to capture supported types, unless this is the only combination
> 
> SUPPORTED_TYPES = [
> "float32_complex64",
> "complex64_complex64",
> "float64_complex128",
> "complex128_complex128",
> ]

Yes, these are the only supported types until users request more. 
They point to input and output types. 
I match the string to the name of the CUDA kernels.

Do you have other implementation ideas in mind?

**Pull request merged**
