### PR TITLE
[WIP] cuSignal Code Refactor - Directory Org/Docs

### PR DESCRIPTION
**Pull request by awthomp**
As mentioned in https://github.com/rapidsai/cusignal/issues/63, a re-organization of the cusignal code directory is needed to reduce code bloat and to allow for an easier on-ramp to new developers. Further, the existing file structure complicates documentation maintenance.

This PR focuses on only components of the pure Python/CuPy codebase and addresses:

- acoustics
- bsplines
- waveforms
- wavelets
- window_functions

Ignoring raw CuPy CUDA kernels, we still need to work on:

- [x] convolution
- [x] filter_design
- [x] filtering
- [x] peak_finding
- [x] spectral_analysis
- [x] array_utils

The initial plan to handle CUDA kernels is to create a `_cuda` folder that contains individual files for each given CUDA kernel. When we get to the point of pushing code to address this, we can revisit the exact structure.

Finally, there were a ton of SciPy Signal/NumPy copy/paste holdovers from beginning days of development. I've adjusted the documentation here to reflect cuSignal and CuPy, as relevant.

--
This PR targets https://github.com/rapidsai/cusignal/issues/63
This PR targets https://github.com/rapidsai/cusignal/issues/58

### CODE REVIEW

**Comment by GPUtester** [comment]
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

**Comment by awthomp** [comment]
Okay, the bulk of cuSignal codebase has now been reorganized, but the Numba CUDA and raw CuPy CUDA kernels still reside in `_upfirdn.py`, `_spectral.py`, and `_signaltools.py`. We still need to reorganize:

- [ ] `convolve2d`
- [ ] `convolve1d`
- [ ] `correlate2d`
- [ ] `correlate1d`
- [ ] `upfirdn`
- [ ] `lombscargle`

We'll also take this opportunity to deprecate the Numba CUDA kernels, but we should keep them _somewhere_ for reference and to tell the Python -> CuPy -> Numba CUDA -> Raw CuPy CUDA story.

**Comment by awthomp** [comment]
@mnicely, @dicta, @boonedoggle, @BradReesWork and @gmarkall  -- I'd like to get your thoughts on how to handle the CUDA kernels in cuSignal. My immediate plan was to have a folder called `_cuda` that basically splits out each CUDA kernel into its own file. There'd additionally be a `cuda_utils.py` file that contains tools for preloading and precompiling the kernels.

I started to re-org but realized I don't really understand how the CuPy CUDA Kernel pre-compilation  and caching works :). Since you all are more involved (or have the potential to be more involved) with the raw CUDA kernel development, I'd like your views to shape how we organize this.

If you pull down a local copy of this PR, you'll notice the new codebase structure. All the Numba and raw CuPy Kernels are in the `_*.py` files it the `cusignal/python/cusignal` directory.

You *should* be able to write to this branch to update the PR. If not, let me know. We can also discuss merging this WIP PR and working on the CUDA re-org in a follow-up.

Thoughts?

**Comment by awthomp** [comment]
Spoke to @dicta this morning, and he suggested keeping the CUDA kernels as close to the given operation as needed. In other words, if you're working on `convolve2d`, it would make more sense for the CUDA kernel to be in the `convolution` rather than `cuda`. 

Concerning kernel compilation and caching, it would make sense to have a newly defined class to manage these operations and management. Here, it'd make sense to store this in a `cuda` folder and potentially move some of the memory management stuff (currently in `utils.arraytools`) there.

In summary, I think the current plan is:
* Keep CUDA kernels and wrappers close to the given operation. E.g. create a file called convolve_cuda.py in `convolution` for 1D/2D convolution and `correlate_cuda.py` in `convolution` for 1D/2D correlation.
* Create `cuda` folder and move functions like `populate_kernel_cache` and `precompile_kernels` to a newly defined class.

We also need to look at how subpackages are handled. I'd like to mimic SciPy Signal as much as possible, and currently, SciPy seemingly packages with `signal` and `signal.windows`. cuSignal has all functionalities incorporated into the base package, like SciPy, but with the refactor, `cusignal.windows` will throw an error. The user would have to import `cusignal.window_functions.windows`. Further, we need to avoid double declarations if a user wants to only import one of the subpackages like `acoustics`. It should be: `from cusignal import acoustics` and then `acoustics.rceps` works rather than having to call `acoustics.cepstrum.rceps`

**Comment by awthomp** [comment]
>We also need to look at how subpackages are handled. I'd like to mimic SciPy Signal as much as possible, and currently, SciPy seemingly packages with signal and signal.windows. cuSignal has all functionalities incorporated into the base package, like SciPy, but with the refactor, cusignal.windows will throw an error. The user would have to import cusignal.window_functions.windows. Further, we need to avoid double declarations if a user wants to only import one of the subpackages like acoustics. It should be: from cusignal import acoustics and then acoustics.rceps works rather than having to call acoustics.cepstrum.rceps

The cuSignal API now matches what you'd expect in SciPy Signal, where applicable. I changed the name of `window_functions` to `windows`, so now the user can:

```python
import cusignal
cusignal.windows.hann()
```

**Comment by awthomp** [comment]
We are going to split this PR into 2. With a later one addressing the CUDA Kernel reorg.

**Pull request merged**
