### PR TITLE
[PR-REVIEW] Load fatbin at runtime

### PR DESCRIPTION
**Pull request by mnicely**
This PR is to investigate the use of loading kernels via PTX and cubins. Instead of compiling them at runtime. 

The idea is to skip the process from Source Code to PTX or cubin. This should eliminate the need to precompile desired kernels, making the UI a little more friendly. 

There are pros and cons to both PTX and cubin.

### PTX
Pro: We can choose a single architecture (default 3.0) and any hardware will JIT based on Compute Capability.
Con: This can leave performance on the table and can be slower than cubins

### Cubin
Pro: Optimal performance and (slightly) faster load because it skip the JIT
Con: Requires a cubin for each supported architecture (i.e. sm30, sm35, sm50, sm52, sm60, sm62, sm70, sm72, sm75, sm80)

Each methode required more space for files and cu file (if we decide to load it)

Currently, using PTX method.

Anecdotal results. PTX and cubin is ~18x faster on first pass
```bash
SOURCE CODE
Time(%)      Total Time   Instances         Average         Minimum         Maximum  Range               
-------  --------------  ----------  --------------  --------------  --------------  --------------------
   78.3       259557232         100       2595572.3         2163073         2954536  gpu_lombscargle_4   
   18.9        62547903           1      62547903.0        62547903        62547903  gpu_lombscargle_0 <-- 
    1.0         3339638           1       3339638.0         3339638         3339638  gpu_lombscargle_1   
    0.9         2960195           1       2960195.0         2960195         2960195  gpu_lombscargle_2   
    0.9         2951219           1       2951219.0         2951219         2951219  gpu_lombscargle_3
PTX
Time(%)      Total Time   Instances         Average         Minimum         Maximum  Range               
-------  --------------  ----------  --------------  --------------  --------------  --------------------
   95.2       247349403         100       2473494.0         2121631         2904074  gpu_lombscargle_4   
    1.3         3447313           1       3447313.0         3447313         3447313  gpu_lombscargle_0 <--  
    1.2         3234977           1       3234977.0         3234977         3234977  gpu_lombscargle_1   
    1.1         2904661           1       2904661.0         2904661         2904661  gpu_lombscargle_2   
    1.1         2902191           1       2902191.0         2902191         2902191  gpu_lombscargle_3
CUBIN
Time(%)      Total Time   Instances         Average         Minimum         Maximum  Range               
-------  --------------  ----------  --------------  --------------  --------------  --------------------
   95.2       239095813         100       2390958.1         2065998         2840041  gpu_lombscargle_4   
    1.3         3325468           1       3325468.0         3325468         3325468  gpu_lombscargle_0 <--  
    1.3         3163933           1       3163933.0         3163933         3163933  gpu_lombscargle_1   
    1.1         2828210           1       2828210.0         2828210         2828210  gpu_lombscargle_2   
    1.1         2823180           1       2823180.0         2823180         2823180  gpu_lombscargle_3
```

### CODE REVIEW

**Comment by GPUtester** [comment]
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

**Comment by mnicely** [comment]
Although not explicitly documented in CuPy documentation. I have been able to load a fatbin into a RawModule in accordance with the CUDA Driver API.

Doing so allows for the following:
1. A fatbin requires less space than multiple cubins and ptx files
2. One single fatbin is easier to maintain than multiple cubins and ptx files
3. With a fatbin, no additional logic is required to select appropriate binary or ptx based on compute capability

Next steps.
1. Build fatbins, manual and perform benchmarks.
2. Create cmake to automatically build fatbins during cuSignal build process.

Notes:
1. Using `cuModuleLoad` doesn't allow for C++ name-mangling. Therefore, CUDA kernels will need to be wrapped with `extern "C"`. Example - https://github.com/cupy/cupy/issues/3185#issuecomment-649064011
2. CuPy RawModule code will be moved to cu files, which will reside in a **cpp** folder. Similar to other RAPIDS APIs
3. Fatbins will be sister folders under a **fatbin** folder.

**Comment by awthomp** [comment]
CC @leofang

Leo -- Wanted to give you a heads up on some of the great work @mnicely has done loading cubins at runtime and avoiding a JIT overhead. Maybe there's something here that we can encapsulate and upstream to cupy?

**Comment by mnicely** [comment]
@awthomp With the move to loading fatbins at runtime. I'm not sure there's a need for `cusignal.precompile`.
Let me know what you think. 
Instead of removing it in 0.15, we can deprecate and get feedback.
Remove in 0.16 if there are no issues.

**Comment by leofang** [comment]
> Leo -- Wanted to give you a heads up on some of the great work @mnicely has done loading cubins at runtime and avoiding a JIT overhead. Maybe there's something here that we can encapsulate and upstream to cupy?

Thanks for pinging me, @awthomp! I have subscribed to this PR! 😁 But after a quick skim-over I am not sure what needs to be upstreamed. RawModule does support fatbin and other formats that `cuModuleLoad` supports. I guess we just need to update its docstring. Did I miss anything?

@mnicely This is very interesting. Is there a guarantee that loading fatbins would first search for the cubin for the corresponding arch, and perform JIT from PTX code if not found?

**Comment by mnicely** [comment]
> @mnicely This is very interesting. Is there a guarantee that loading fatbins would first search for the cubin for the corresponding arch, and perform JIT from PTX code if not found?

The search pattern is based on the `CUjit_fallback` flag, which I believe defaults to `CU_PREFER_PTX`.

I tested this by compiling a binary and ptx for CC60 and running it on my RTX Titan CC75. It worked successfully.
I also showed the negative test worked by only compiling a binary for CC60.

Using the fatbin eliminates logic for selecting the cubin and ptx files based on user architecture

The hardest path, at the moment, is setting up the relative paths correctly to the fatbins after building them.

**Comment by mnicely** [comment]
@awthomp @BradReesWork @raydouglass 
For the life of me, I can't figure out why the build process for CI is different than my local machine (where all pytests pass)

When I look at the error reports, I can see that the fatbins are not being built and copied to the correct folders.

I've updated `build.sh` and `setup.py` to do this locally. What am I missing?

**Comment by mnicely** [comment]
@BradReesWork 
Once we get this working, maybe someone from the RAPIDS team can help move my build process for fatbins to CMake?

**Comment by mnicely** [comment]
Hi @rlratzel. Do you have time to help me get past our CI issue?

With this PR, I've moved my CUDA code to cu files and I'm building fatbins that will be loaded at runtime.
It works fine on my location machine, but not with CI.

I don't think the fatbins are getting built...
If they are, they are not able to be found.

**Comment by mnicely** [comment]
@leofang Have you ever tried relocatable code and mixing NVRTC compiling at runtime and loading from a fatbin?

Example, I have a `__global__` function that is templated and requires runtime inputs (RawModule). That function calls multiple `__device__` helper functions, that are also templated, but don't require runtime time input. Therefore the helper functions can be precompiled (NVCC) into a fatbin. 

I'm wondering if I enable -rdc on both the CuPy RawModule and the NVCC, can I have the `__global__` function access the `__device__` functions.

**Comment by mnicely** [comment]
## Info

### Folder Structure
This PR adds the following folders and files.

```
├── cpp
│   ├── build
│   ├── scripts
│   │   └── run-clang-format.py
│   └── src
│       ├── convolution
│       │   └── _convolution.cu
│       ├── estimation
│       ├── filtering
│       │   ├── _sosfilt.cu
│       │   └── _upfirdn.cu
│       ├── io
│       │   ├── _reader.cu
│       │   └── _writer.cu
│       └── spectral_analysis
│           └── _spectral.cu
```

Fatbins are then compiled with `cusignal/build.sh` and outputted in the following folders.

```
├── python
│   ├── ...
│   ├── cusignal
│   │   ├── ...
│   │   ├── convolution
│   │   │   ├── _convolution_cuda.py
│   │   │   ├── _convolution.fatbin
│   │   │   ├── convolution_utils.py
│   │   │   ├── convolve.py
│   │   │   ├── correlate.py
│   │   │   ├── __init__.py
│   │   │   └── __pycache__
│   │   ├── ...
│   │   ├── filtering
│   │   │   ├── filtering.py
│   │   │   ├── __init__.py
│   │   │   ├── __pycache__
│   │   │   ├── resample.py
│   │   │   ├── _sosfilt_cuda.py
│   │   │   ├── _sosfilt.fatbin
│   │   │   ├── _upfirdn_cuda.py
│   │   │   └── _upfirdn.fatbin
│   │   ├── ...
│   │   ├── io
│   │   │   ├── __init__.py
│   │   │   ├── __pycache__
│   │   │   ├── _reader_cuda.py
│   │   │   ├── _reader.fatbin
│   │   │   ├── reader.py
│   │   │   ├── _writer_cuda.py
│   │   │   ├── _writer.fatbin
│   │   │   └── writer.py
│   │   ├── ...
│   │   ├── spectral_analysis
│   │   │   ├── __init__.py
│   │   │   ├── __pycache__
│   │   │   ├── _spectral_cuda.py
│   │   │   ├── _spectral.fatbin
│   │   │   └── spectral.py
│   │   ...
│   ...
...
```

### Fatbins
Binaries for all architectures compatible with CUDA 10.2 are compiled in the each fatbin.
Along with a PTX for CC7.5, the highest compatible architecture.

At compile time the appropriate binary will be chosen. There two scenarios where this will not happen.
1. If the compute capability is less than 3.5, cuSignal will fail to run.
2. If the compute capability is greater than CC7.5, the ptx will be loaded and compiled into a cubin.

In later versions of cuSignal, compatible with CUDA 11+, more cubins can be added.

All fatbin cost less than 5MB.

**Comment by leofang** [comment]
I myself have not tried this, but I guess it's doable. I've added the support of separate compilation to CuPy, and there the key is to call `cuLinkAddFile` to add the device runtime before completing the linking. What you need is to call it one more time to add your fatbin -- note there is an option `CU_JIT_INPUT_FATBINARY` for this purpose. 

(Sorry, it's hard to add links on my phone, let me know if you need pointers😅)

**Comment by mnicely** [comment]
What you described is very similar to this I think... https://parallel-computing.pro/index.php/9-cuda/40-use-cuda-7-0-nvrtc-with-thrust

But I'm guessing CuPy doesn't have an abstract level to do this :smile:

**Comment by mnicely** [comment]
Thanks @rlratzel!

Here is the code that builds the fatbins. I'm currently running it in `build.sh`
Do you think this can put in a cmake? And that cmake be called from `python/setup.py`?

```bash
################################################################################
# Build fatbins
SRC="cpp/src"
FAT="python/cusignal"
FLAGS="-std=c++11"

if hasArg -p; then
    FLAGS="${FLAGS} -Xptxas -v -Xptxas -warn-lmem-usage -Xptxas -warn-double-usage"
fi

GPU_ARCH="--generate-code arch=compute_35,code=sm_35 \
--generate-code arch=compute_35,code=sm_37 \
--generate-code arch=compute_50,code=sm_50 \
--generate-code arch=compute_50,code=sm_52 \
--generate-code arch=compute_53,code=sm_53 \
--generate-code arch=compute_60,code=sm_60 \
--generate-code arch=compute_61,code=sm_61 \
--generate-code arch=compute_62,code=sm_62 \
--generate-code arch=compute_70,code=sm_70 \
--generate-code arch=compute_72,code=sm_72 \
--generate-code arch=compute_75,code=[sm_75,compute_75]"

echo "Building Convolution kernels..."
FOLDER="convolution"
mkdir -p ${FAT}/${FOLDER}/
nvcc --fatbin ${FLAGS} ${GPU_ARCH} ${SRC}/${FOLDER}/_convolution.cu -odir ${FAT}/${FOLDER}/ &

echo "Building Filtering kernels..."
FOLDER="filtering"
mkdir -p ${FAT}/${FOLDER}/
nvcc --fatbin ${FLAGS} ${GPU_ARCH} ${SRC}/${FOLDER}/_upfirdn.cu -odir ${FAT}/${FOLDER}/ &
nvcc --fatbin ${FLAGS} ${GPU_ARCH} ${SRC}/${FOLDER}/_sosfilt.cu -odir ${FAT}/${FOLDER}/ &

echo "Building IO kernels..."
FOLDER="io"
mkdir -p ${FAT}/${FOLDER}/
nvcc --fatbin ${FLAGS} ${GPU_ARCH} ${SRC}/${FOLDER}/_reader.cu -odir ${FAT}/${FOLDER}/ &
nvcc --fatbin ${FLAGS} ${GPU_ARCH} ${SRC}/${FOLDER}/_writer.cu -odir ${FAT}/${FOLDER}/ &

echo "Building Spectral kernels..."
FOLDER="spectral_analysis"
mkdir -p ${FAT}/${FOLDER}/
nvcc --fatbin ${FLAGS} ${GPU_ARCH} ${SRC}/${FOLDER}/_spectral.cu -odir ${FAT}/${FOLDER}/ &

wait
```

**Comment by rlratzel** [comment]
> Here is the code that builds the fatbins. I'm currently running it in `build.sh`
> Do you think this can put in a cmake? And that cmake be called from `python/setup.py`?

I think that can be moved out of the build script and into (some part of) cmake, where it will generate the Makefile with those calls. From there, `python/setup.py` should be able to build those extensions via the updated/generated Makefile. Disclaimer: I'm assuming some of these things based on how other repos build, but I'll find out the specifics when we start the updates.

@mnicely are you thinking you want the cmake updates as part of this PR or a separate followup PR?

**Comment by mnicely** [comment]
> @mnicely are you thinking you want the cmake updates as part of this PR or a separate followup PR?

@rlratzel Let's work it in another PR after this is pushed. :smile:

**Comment by mnicely** [comment]
After further considerations. We've decided to remove `precompile_kernels` from 0.15.

This is because, now all kernel calls will work as if `precompile_kernels` was called at import.

**Comment by mnicely** [comment]
Closes #129

**Pull request merged**
