### PR TITLE
[REVIEW] Update cuSignal to Numba >= 0.49 and update preferred versioning in conda environments

### PR DESCRIPTION
**Pull request by awthomp**
This PR does the following:
* Remove Complex scalar check on Numba <= 0.48 vs Numba > 0.48; enforce 0.48 or newer for cuSignal
* Updates conda environments to use Numba >= 0.49 and CuPy >= 7.2
* Remove unnecessary aarch64 packages

### CODE REVIEW

**Comment by GPUtester** [comment]
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

**Comment by awthomp** [comment]
@raydouglass -- we'd like to upgrade the minimum Numba version for cuSignal to 0.49, but it looks like CI is erroring out due to 0.48 in the environment. Anything I need to change on my end?

**Comment by awthomp** [comment]
> Any reason we can't use CuPy 7.4.0 over 7.3.0 in 0.14?
> 
> with
> `cupy>=7.3.0`

We certainly can, but this is more a function of setting the minimum requirement. Conda should get the most recent version of the library with the install, AFAIK.

**Comment by mnicely** [comment]
Gotcha!
________________________________

**Pull request merged**
