### PR TITLE
[REVIEW] Updated decimate function to use an existing FIR window

### PR DESCRIPTION
**Pull request by boonedoggle**
This reduces computation time by not recreating the window it every call.

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by awthomp** [comment]
rerun tests

**Comment by BradReesWork** [comment]
okay to test

**Comment by BradReesWork** [comment]
ok to test

**Comment by BradReesWork** [comment]
@boonedoggle great work, just a few minor style issues to fix before I can merge the code

**Pull request merged**
