### PR TITLE
[REVIEW] Add estimation example

### PR DESCRIPTION
**Pull request by mnicely**
Create folder to store test scripts.

### CODE REVIEW

**Comment by GPUtester** [comment]
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

**Comment by mnicely** [comment]
> @mnicely -- Is there a reason this couldn't be a Jupyter Notebook where you can also explain some of your design decisions as well? On closer look, I'm unclear of the delineation between 'scripts' and 'notebooks'.

Moved the script to a jupyter notebook.
Let you me know what you think.

**Comment by awthomp** [comment]
@mnicely -- Looks like CI is hitting the following error:

```
ModuleNotFoundError: No module named 'filterpy'
```

**Comment by mnicely** [comment]
Rats. That’s the Python package for the serial code. I need to figure out where to put ‘Fonda install -c conda-forge filterpy’

**Comment by awthomp** [comment]
> Rats. That’s the Python package for the serial code. I need to figure out where to put ‘conda install -c conda-forge filterpy’

Try the following:

- [meta.yaml](https://github.com/rapidsai/cusignal/blob/branch-0.15/conda/recipes/cusignal/meta.yaml)
- [conda environments](https://github.com/rapidsai/cusignal/tree/branch-0.15/conda/environments)

**Comment by ajschmidt8** [comment]
@awthomp, @mnicely, to test out a new package with CI, you'll need to (temporarily) add the `conda install` command here.
https://github.com/rapidsai/cusignal/blob/branch-0.15/ci/gpu/build.sh#L50-L52

Once you commit that change, CI will re-run on this PR with the package installed. If everything builds successfully, you can revert the temporary `conda install` and add the `filterpy` package to the `rapids-build-env` recipe located [here](https://github.com/rapidsai/integration/tree/branch-0.15/conda/recipes/rapids-build-env).

Happy to help with this if anything is unclear.

**Comment by awthomp** [comment]
> @awthomp, @mnicely, to test out a new package with CI, you'll need to (temporarily) add the `conda install` command here.
> https://github.com/rapidsai/cusignal/blob/branch-0.15/ci/gpu/build.sh#L50-L52
> 
> Once you commit that change, CI will re-run on this PR with the package installed. If everything builds successfully, you can revert the temporary `conda install` and add the `filterpy` package permanently to the `rapids-build-env` recipe located [here](https://github.com/rapidsai/integration/tree/branch-0.15/conda/recipes/rapids-build-env).
> 
> Happy to help with this if anything is unclear.

**Comment by awthomp** [comment]
Sorry guys, accidentally closed the PR!

@mnicely -- can you make the changes that @ajschmidt8 suggested?

**Comment by mnicely** [comment]
The Kalman filter function requires CuPy v8.0.0b4+. Will skip notebook testing in cuSignal 0.15 because CuPy 7.X is default.

**Comment by mnicely** [comment]
rerun tests

**Pull request merged**
