### PR TITLE
[REVIEW] Add c++17 if constexpr to reader.cu

### PR DESCRIPTION
**Pull request by mnicely**
With C++17, we can use `if constexpr` to evaluate if statements at compile time. This is especially useful if we are choosing a path based off type, which is known at compile time. 

This has been added to the IO reader to greatly reduce branching in logic.

### CODE REVIEW

**Comment by GPUtester** [comment]
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

**Comment by awthomp** [comment]
> Looks good; let's find a way not to have the fatbins update with each source build, though!

And on that topic, looks like there's a merge conflict with them, @mnicely!

**Comment by mnicely** [comment]
@ajschmidt8 Can you remind me how to force CUDA 11 + CuPy v8 through CI?

**Comment by ajschmidt8** [comment]
> @ajschmidt8 Can you remind me how to force CUDA 11 + CuPy v8 through CI?
> 
> I need it for C++17 and we are requiring it for cuSignal 0.16.

@mnicely, just saw this today, but it looks like you got a response in Slack. let me know if any additional information is needed.

**Pull request merged**
