### PR TITLE
[REVIEW] Implementation of Raw CuPy Module for upfirdn

### PR DESCRIPTION
**Pull request by awthomp**
This PR closes https://github.com/rapidsai/cusignal/issues/16
 
CC: @mnicely
 
WIP implementation comparing the performance of a raw CuPy CUDA kernel via `RawModule` versus the legacy Numba CUDA kernel. This currently only addresses the 1D case for `upfirdn` and adds an additional parameter for `apply_filter` where:
* `use_numba=True` uses the legacy `upfirdn` CUDA kernel and
* `use_numba=False` uses the CuPy RawModule
 
This is also exposed in `resample_poly`. As an example:
 
```python
import cusignal
import cupy as cp
 
start = 0
stop = 10
num = int(1e8)
resample_up = 2
resample_down = 3
 
gx = cp.linspace(start, stop, num, endpoint=False)
gy = cp.cos(-gx**2/6.0)
 
gf = cusignal.resample_poly(gy, resample_up, resample_down, window=('kaiser', 0.5), use_numba=False)
```
 
Matt has a separate test script that has been profiled via NSIGHT; it's getting about a 4x perf increase. When timed Python, however, I'm getting a ~2x speed decrease in `resample_poly`.
 
There are also Python formatting fixes in this PR and an update to the relevant Jupyter notebook showing the option to use the Numba/Raw CuPy kernel.

### CODE REVIEW

**Comment by gmarkall** [comment]
I think compiling the CuPy kernel for `_raw_apply_1d` on every call is unnecessary and will be expensive - I've tried caching the kernels in https://github.com/gmarkall/cusignal/commit/e3b854c560c65d610bcabf0ff825d01b1740593f - on my test machine (Tesla V100-SXM2-16GB) this makes the call to `resample_poly` with the raw kernel approximately 3x faster than the Numba one by wall time.

```
use_numba=True:

     CPU times: user 288 ms, sys: 52 ms, total: 340 ms
     Wall time: 363 ms
    
use_numba=False:
    
     CPU times: user 116 ms, sys: 4 ms, total: 120 ms
     Wall time: 120 ms
```

**Comment by awthomp** [comment]
Looks great, @gmarkall! Both @mnicely and I didn't realize CuPy wasn't caching the compiled kernel after the first run. Your experiment looks straight forward, and I'm good with rolling it into the baseline code. Can you commit to this PR, or do you need to create a separate one that merges after this?

**Comment by gmarkall** [comment]
I can't commit to the PR branch as I don't have write access to github.com/awthomp/cusignal-dev repo - I'll create a separate PR that merges after this one.

**Comment by gmarkall** [comment]
PR #26 created for the merge afterwards.

**Comment by gmarkall** [comment]
It's also worth considering that at the moment the notebook example is comparing a raw kernel operating on 32-bit types with a Numba kernel operating on 64-bit types - for example, `gy` in the notebook is a `float64`. Passing this to the raw CuPy kernel appears to initiate a copy from `float64` to `float32`, whereas Numba will accept the `float64` and do all operations on `float64` data, which carries a performance penalty. Modifying the Numba kernel so that it only accepts `float32` (to ensure that nothing is accidentally run with a `float64` while I'm testing) with an explicit signature:

```diff
diff --git a/python/cusignal/_upfirdn.py b/python/cusignal/_upfirdn.py
index 54f887c..aacab2f 100644
--- a/python/cusignal/_upfirdn.py
+++ b/python/cusignal/_upfirdn.py
@@ -12,7 +12,7 @@
 # limitations under the License.
 
 import cupy as cp
-from numba import cuda
+from numba import cuda, float32, int32, void
 import math
 
 
@@ -94,7 +94,7 @@ def _apply(x, h_trans_flip, out, up, down, axis=-1):
             h_idx += 1
 
 
-@cuda.jit(fastmath=True)
+@cuda.jit(void(float32[:], float32[:], float32[:], int32, int32, int32), fastmath=True)
 def _apply_1d(x, h_trans_flip, out, up, down, axis=-1):
 
     X = cuda.grid(1)
```

and then changing the declaration of `gx` and `gy` in the notebook:

```python
gx = cp.linspace(start, stop, num, endpoint=False, dtype=np.float32)
gy = cp.cos(-gx**2/6.0)
```

results in the following times:

```
Numba:
    CPU times: user 4 ms, sys: 20 ms, total: 24 ms
    Wall time: 21.5 ms

CuPy:
    CPU times: user 8 ms, sys: 4 ms, total: 12 ms
    Wall time: 10.5 ms
```

which closes the gap to 2x performance from CuPy - still some more improvement to do on the Numba side :-)

**Comment by awthomp** [comment]
Since this PR gives the user the option to roll back to the default Numba CUDA kernel (in fact, it's enabled by default), I'm going to recommend merging this PR.

**Comment by awthomp** [comment]
@mnicely -- this PR contains the `int` raw CuPy kernel. Do you want it removed?

**Comment by mnicely** [comment]
@awthomp If it's not too late, I suggest we removed the **int** kernel from the Raw Module. It is technically dead code, because it will never be reached because any **int** input is promoted to **float**.

**Pull request merged**
