### PR TITLE
[REVIEW] Fixing issue when reading sigmf data from parent folder

### PR DESCRIPTION
**Pull request by drabastomek**
1. Change to the `.read_sigmf(...)` method to handle reading metadata file (when `meta_file` not specified) from the parent folder that requires `..` escapes. Current solution does not handle this use case.

2. Tested locally. No unit test written.

3. Closing #279

4. Ready for review.

5. Ready for review. 

6. Ready for review. No additional changes expected.

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Review by awthomp — APPROVED** [review]
Looks good! Thanks for the PR, @drabastomek!

**Comment by awthomp** [comment]
@BradReesWork -- can you add Tom to the whitelist and `ok to test` this PR?

**Review by BradReesWork — APPROVED** [review]

**Comment by BradReesWork** [comment]
ok to test

**Comment by drabastomek** [comment]
Looks like the pr-builder didn't go thru. Seems like a test config problem

**Comment by awthomp** [comment]
rerun tests

**Comment by GPUtester** [comment]
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

**Comment by BradReesWork** [comment]
@drabastomek - can you update the ChangeLog with your PR?

**Comment by awthomp** [comment]
rerun tests

**Pull request merged**
