### PR TITLE
[REVIEW] Add notebook testing to CI

### PR DESCRIPTION
**Pull request by dillon-cullinan**
Add notebook testing to PR gpuCI tests.

### CODE REVIEW

**Comment by GPUtester** [comment]
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

**Comment by BradReesWork** [comment]
rerun tests

**Comment by dillon-cullinan** [comment]
Need to test installing pytorch inside the notebook test script as our RAPIDS environments have conflicts with pytorch.

**Comment by dillon-cullinan** [comment]
@awthomp @BradReesWork This should be ready to merge now. Two notebook failures caused by "File not found". Would you like to fix these before merging and rerun this or some other time?

**Pull request merged**
