### PR TITLE
fix filtering.resample output for even values of num parameter

### PR DESCRIPTION
**Pull request by mattkinsey**
This just fixes the handling of the nyquest frequency bins when resampling using the FFT method (`filtering.resample`). 

Without enforcing the fourier space be hermitian symmetric like this, the resampled output had a few undesirable properties:

1. It had a different integrated power spectrum than the input
2. It was not reversible i.e. `resample(resample(y, <larger size than y>), <original y size>) != y`
3. The output disagreed with `scipy.signal.resample`. The max error was around 1e-2 in my application.

Thanks

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

Admins can comment `ok to test` to allow this one PR to run or `add to allowlist` to allow all future PRs from the same author to run.

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

Admins can comment `ok to test` to allow this one PR to run or `add to allowlist` to allow all future PRs from the same author to run.

**Comment by awthomp** [comment]
ok to test

**Comment by awthomp** [comment]
Hey @mattkinsey ! Thanks for the PR; looks great! I had to change the base branch you were merging into (branch-22.12 rather than main) and fix some minor merge conflicts, but otherwise looks good. We'll get this merged ASAP. Thanks for your contributions, and Happy Thanksgiving!

**Review by awthomp — APPROVED** [review]

**Comment by awthomp** [comment]
rerun tests

**Comment by awthomp** [comment]
@gpucibot merge

**Pull request merged**
