### PR TITLE
[REVIEW] Use Numba 0.49+ API where required

### PR DESCRIPTION
**Pull request by dicta**
https://github.com/numba/numba/pull/5197 refactors many of Numba's submodules. Mirror the required import changes in cusignal.

This keeps cusignal in sync with numba master and the 0.49 release candidate but breaks compatibility with the current numba release (0.48).

This should go in eventually but also needs to make sure we keep compatibility with whatever version of numba we're getting in the conda channels selected by our packaging (and certainly updates the minimum required version) - need help with this part.

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by awthomp** [comment]
rerun tests

**Comment by awthomp** [comment]
@BradReesWork -- can you comment on this part:

> This should go in eventually but also needs to make sure we keep compatibility with whatever version of numba we're getting in the conda channels selected by our packaging (and certainly updates the minimum required version) - need help with this part.

I'm guessing we just need to be more explicit on the Numba version used in https://github.com/rapidsai/cusignal/blob/branch-0.14/conda/environments/cusignal_base.yml

**Comment by awthomp** [comment]
rerun tests

**Comment by mnicely** [comment]
@gmarkall Do you know when Numba 49 will be out of RC and be considered stable/latest?

**Comment by gmarkall** [comment]
@mnicely I think this may occur within the next couple of weeks.

**Comment by gmarkall** [comment]
Also - the original import (`from numba.types.scalars import Complex`) should have been working with 0.49 because there are shim modules that enable importing from the old path, but there were various issues with the shims, e.g.:

https://github.com/numba/numba/issues/5528
https://github.com/numba/numba/issues/5484
https://github.com/numba/numba/issues/5487
https://github.com/numba/numba/issues/5466

Once 0.49RC2 is out, the original code may (should!) still work.

If it's preferred to avoid being more specific about the version of Numba we use, something like the following should provide compatibility with both versions:

```diff
diff --git a/python/cusignal/_upfirdn.py b/python/cusignal/_upfirdn.py
index 033d5ac..ed5a17d 100644
--- a/python/cusignal/_upfirdn.py
+++ b/python/cusignal/_upfirdn.py
@@ -17,7 +17,12 @@ from string import Template
 
 import cupy as cp
 from numba import complex64, complex128, cuda, float32, float64, int64, void
-from numba.core.types.scalars import Complex
+try:
+    # Numba <= 0.49
+    from numba.types.scalars import Complex
+except ImportError:
+    # Numba >= 0.49
+    from numba.core.types.scalars import Complex
 
 _numba_kernel_cache = {}
 _cupy_kernel_cache = {}
```

**Comment by boonedoggle** [comment]
If you try the import in that order with a `try/except`, you will get the following warning every time `cusignal` is imported:
```
Import requested from: 'numba.types', please update to use 'numba.core.types' or pin to
Numba version 0.48.0. This alias will not be present in Numba version 0.50.0.
```

Maybe reverse the order? This seems to suppress the warning for both cases.

```
try:
    # Numba >= 0.49
    from numba.core.types.scalars import Complex
except ImportError:
    # Numba <= 0.49
    from numba.types.scalars import Complex
```

**Comment by BradReesWork** [comment]
> @BradReesWork -- can you comment on this part:
> 
> > This should go in eventually but also needs to make sure we keep compatibility with whatever version of numba we're getting in the conda channels selected by our packaging (and certainly updates the minimum required version) - need help with this part.
> 
> I'm guessing we just need to be more explicit on the Numba version used in https://github.com/rapidsai/cusignal/blob/branch-0.14/conda/environments/cusignal_base.yml

You should have min / max version numbers for external libraries in the conda environment file

**Comment by awthomp** [comment]
rerun tests

**Comment by awthomp** [comment]
Weird -- looks like my push to @dicta's fork isn't updating the main PR if you look at 'files changed'. Let's confirm that https://github.com/rapidsai/cusignal/pull/53/commits/36ed41b15b5feb33a14010aa4356c447884aefc8 gets included in the merge.

**Comment by awthomp** [comment]
> Weird -- looks like my push to @dicta's fork isn't updating the main PR if you look at 'files changed'. Let's confirm that [36ed41b](https://github.com/rapidsai/cusignal/commit/36ed41b15b5feb33a14010aa4356c447884aefc8) gets included in the merge.

Nevermind -- they're showing now.

**Comment by awthomp** [comment]
rerun tests

**Comment by awthomp** [comment]
@raydouglass @BradReesWork Looks like CI is stuck on this PR. Any chance ya'll can look behind the curtain so we can get this merged?

**Comment by raydouglass** [comment]
ok to test

**Pull request merged**
