### PR TITLE
Add morlet2

### PR DESCRIPTION
**Pull request by mnicely**
Noticed morlet2 was missing.

This PR adds it and some tests.

### CODE REVIEW

**Review by awthomp — CHANGES_REQUESTED** [review]
@mnicely -- looks like you have stuff with your polyphase channelizer bug fix in here too. Mind merging this with main instead?

**Comment by mnicely** [comment]
Okay. I’ll modify in the morning

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by mnicely** [comment]
@awthomp Should be fixed now.

**Comment by mnicely** [comment]
rerun tests

**Review by awthomp — APPROVED** [review]

**Comment by awthomp** [comment]
@gpucibot merge

**Pull request merged**
