### PR TITLE
[REVIEW] Added AIR-T conda recipe so that cuSignal officially support the AIR_T

### PR DESCRIPTION
**Pull request by boonedoggle**
Added AIR-T conda recipe so that cuSignal officially support the AIR_T

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by awthomp** [comment]
okay to test

**Comment by awthomp** [comment]
ok to test

**Comment by awthomp** [comment]
@BradReesWork -- I can't get CI kicked on this PR, but I think it's good to merge.

**Comment by awthomp** [comment]
add to whitelist

**Pull request merged**
