### PR TITLE
[REVIEW] Synchronization issue with cusignal testing

### LINKED ISSUE #220: [BUG] Synchronization issue with cusignal testing
**Describe the bug**
While working with @mnicely on #219, found that for the kaiser_beta test requires synchronization in order to get desired benchmark results and metrics. 

**Steps/Code to reproduce bug**
To see the original issue, without synchronization I am using the below code block as the KaiserBeta test. 

```
    @pytest.mark.benchmark(group="KaiserBeta")
    @pytest.mark.parametrize("a", [1, 22, 51])
    class TestKaiserBeta:
        def cpu_version(self, a):
            return signal.kaiser_beta(a)

        @pytest.mark.cpu
        def test_kaiser_beta_cpu(self, benchmark, a):
            benchmark(self.cpu_version, a)

        def test_kaiser_beta_gpu(self, gpubenchmark, a):

            output = gpubenchmark(signal.kaiser_beta, a)

            key = self.cpu_version(a)
            assert array_equal(cp.asnumpy(output), key)
```

In order to avoid the 
```
    @pytest.mark.benchmark(group="KaiserBeta")
    @pytest.mark.parametrize("a", [1, 22, 51])
    class TestKaiserBeta:
        def cpu_version(self, a):
            return signal.kaiser_beta(a)
        
        def gpu_version(self, a):
            ans = cusignal.kaiser_beta(a)
            cp.cuda.runtime.deviceSynchronize()
            return ans

        @pytest.mark.cpu
        def test_kaiser_beta_cpu(self, benchmark, a):
            benchmark(self.cpu_version, a)

        def test_kaiser_beta_gpu(self, gpubenchmark, a):

            output = gpubenchmark(self.gpu_version, a)

            key = self.cpu_version(a)
            assert array_equal(cp.asnumpy(output), key)
```
Both scenarios can be run using 
```
pytest -v -k kaiser_beta --benchmark-enable --benchmark-columns=mean
```
**Expected behavior**
In the scenario without the additional `cp.cuda.runtime.deviceSynchronize()` we see these results:

```
------- benchmark 'KaiserBeta': 6 tests -------(6/6)
Name (time in ns)                Mean          
-----------------------------------------------
test_kaiser_beta_gpu[1]       72.2238 (1.0)    
test_kaiser_beta_gpu[51]     101.5226 (1.41)   
test_kaiser_beta_cpu[1]      149.5620 (2.07)   
test_kaiser_beta_gpu[22]     163.8500 (2.27)   
test_kaiser_beta_cpu[51]     167.9316 (2.33)   
test_kaiser_beta_cpu[22]     241.9258 (3.35)   
-----------------------------------------------
```

Then with the added `cp.cuda.runtime.deviceSynchronize()` we see these results
```
------- benchmark 'KaiserBeta': 6 tests -------(6/6)
Name (time in ns)                Mean          
-----------------------------------------------
test_kaiser_beta_cpu[1]      151.5113 (1.0)    
test_kaiser_beta_cpu[51]     183.4480 (1.21)   
test_kaiser_beta_cpu[22]     235.7553 (1.56)   
test_kaiser_beta_gpu[1]      801.9767 (5.29)   
test_kaiser_beta_gpu[51]     846.5461 (5.59)   
test_kaiser_beta_gpu[22]     943.0328 (6.22)   
-----------------------------------------------
```

**Environment details (please complete the following information):**

- Environment location: Running on local machine with RTX 6000
- Method of cuSignal install: from source  

**Additional context**
Proposing that the `gpu_version` be added to cusignal tests. Open to feedback about this issue (especially as this is my first one!)

### PR DESCRIPTION
**Pull request by z-ryan1**
Closes #220 

**Info**
This PR is to add synchronization to the existing cusignal tests

### To-do list
- [x] test_acoustics
- [x] test_bsplines
- [x] test_convolution
- [x] test_filter_design
- [x] test_filtering
- [x] test_peak_finding
- [x] test_spectral_analysis
- [x] test_waveforms
- [x] test_wavelets
- [x] test_windows

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by awthomp** [comment]
add to whitelist

**Comment by awthomp** [comment]
ok to test

**Comment by mnicely** [comment]
@z-ryan1 Let's use stream sychronization instead of device synchronization. Much more lightweight.

### Device Sync
```bash
---------- benchmark 'KaiserBeta': 6 tests -----------
Name (time in ns, mem in bytes)         Mean          
------------------------------------------------------
test_kaiser_beta_cpu[1]             144.6260 (1.0)    
test_kaiser_beta_cpu[51]            157.3403 (1.09)   
test_kaiser_beta_cpu[22]            238.3417 (1.65)   
test_kaiser_beta_gpu[1]             768.6711 (5.31)   
test_kaiser_beta_gpu[51]            775.9893 (5.37)   
test_kaiser_beta_gpu[22]            853.5079 (5.90)   
------------------------------------------------------
```

### Stream Sync
```bash
---------- benchmark 'KaiserBeta': 6 tests -----------
Name (time in ns, mem in bytes)         Mean          
------------------------------------------------------
test_kaiser_beta_cpu[1]             145.4373 (1.0)    
test_kaiser_beta_cpu[51]            164.4141 (1.13)   
test_kaiser_beta_cpu[22]            231.1376 (1.59)   
test_kaiser_beta_gpu[1]             524.4655 (3.61)   
test_kaiser_beta_gpu[51]            539.9256 (3.71)   
test_kaiser_beta_gpu[22]            626.2389 (4.31)   
------------------------------------------------------
```

### Code
```python
    @pytest.mark.benchmark(group="KaiserBeta")
    @pytest.mark.parametrize("a", [1, 22, 51])
    class TestKaiserBeta:
        def cpu_version(self, a):
            return signal.kaiser_beta(a)

        def gpu_version(self, a):
            with cp.cuda.Stream.null:
                return cusignal.kaiser_beta(a)

        @pytest.mark.cpu
        def test_kaiser_beta_cpu(self, benchmark, a):
            benchmark(self.cpu_version, a)

        def test_kaiser_beta_gpu(self, gpubenchmark, a):

            output = gpubenchmark(self.gpu_version, a)

            key = self.cpu_version(a)
            assert array_equal(cp.asnumpy(output), key)
```

**Review by BradReesWork — APPROVED** [review]

**Comment by mnicely** [comment]
ok to test

**Comment by mnicely** [comment]
ok to test

**Comment by mnicely** [comment]
ok to test

**Comment by BradReesWork** [comment]
ok to test

**Pull request merged**
