### PR TITLE
Adding CFAR

### PR DESCRIPTION
**Pull request by mbolding3**
Added CFAR routines in 1d and 2d with some basic unit tests.

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by awthomp** [comment]
@ajschmidt8 -- could we add @mbolding3 to the allowlist, please?

**Comment by ajschmidt8** [comment]
ok to test

**Comment by ajschmidt8** [comment]
> @ajschmidt8 -- could we add @mbolding3 to the allowlist, please?

I think the `allowlist` is reserved for NVIDIA employees, but we can still test this PR nonetheless.

**Review by awthomp — APPROVED** [review]
Looks great to me. Thanks so much for the contribution, Mark! Incredible.

**Comment by awthomp** [comment]
@gpucibot merge

**Pull request merged**
