### PR TITLE
Relicense cuSignal as MIT from Apache 2

### PR DESCRIPTION
**Pull request by awthomp**
Copyright and licensing changes to change cuSignal license from Apache-2 to MIT

### CODE REVIEW

**Comment by jakirkham** [comment]
cc @rgommers

**Comment by leofang** [comment]
cc: @kmaehashi @takagi for vis

**Review by raydouglass — APPROVED** [review]

**Review by BradReesWork — APPROVED** [review]

**Comment by kmaehashi** [comment]
Thank you again for the decision to make this transition. I sincerely appreciate Adam and everyone involved in developing this great library! :pray:

Now that the change has merged, CuPy will start adopting code and documentation from cuSignal. We'll try to complete the transition as quickly as possible so that cuSignal users can migrate smoothly.

The very first thing to do is to add this MIT license from cuSignal 😄
https://github.com/cupy/cupy/pull/7816

**Pull request merged**
