### PR TITLE
Change type check to use isinstance instead of str compare

### PR DESCRIPTION
**Pull request by jrc-exp**

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by awthomp** [comment]
ok to test

**Review by awthomp — APPROVED** [review]

**Comment by ajschmidt8** [comment]
ok to test

**Comment by awthomp** [comment]
rerun tests

**Comment by awthomp** [comment]
@gpucibot merge

**Pull request merged**
