### PR TITLE
[REVIEW] Add pytest-benchmark to cuSignal library

### PR DESCRIPTION
**Pull request by mnicely**
### Info
This PR adds pytest-benchmark functionality to the cuSignal library, starting with `signaltools` functions. 

In `pytest.ini` to the `cusignal/python` directory. It will set all of our benchmark parameters and overwrite any defaults we want to change. In this file we set benchmarks be to skipped by default. This can be overwrite by passing `--benchmark-only` to pytest (e.g. `pytest -v --benchmark-only`. It also allows benchmark classes and files/functions to be suffixed with **Bench** and **bench_**, respectively. 

```ini
[pytest]
addopts = 
	--benchmark-min-rounds=25
	--benchmark-warmup=on 
	--benchmark-warmup-iterations=10 
	--benchmark-disable-gc
	--benchmark-skip
python_classes =
	Bench*
	Test*
python_files =
	bench_*
	test_*
python_functions = 
	bench_*
	test_*
```

In `bench_signaltools.py` provides our actual benchmarking code, similar to the testing code already in  `test/test_signaltools.py. Looking at `BenchResample` as an example. 
```python
@pytest.mark.benchmark(group="Resample")
@pytest.mark.parametrize("num_samps", [2 ** 14])
@pytest.mark.parametrize("resample_num_samps", [2 ** 12, 2 ** 16])
@pytest.mark.parametrize("window", [("kaiser", 0.5)])
# Bench is required in class name for the test to be active
class BenchResample:
    # This function will ensure the GPU version is getting the correct answer
    def cpu_version(self, cpu_sig, resample_num_samps, window):
        return signal.resample(cpu_sig, resample_num_samps, window=window)

    # bench_ is required in function name to be searchable with -k parameter
    def bench_resample_cpu(
        self, resample_setup, benchmark, num_samps, resample_num_samps, window
    ):
        cpu_sig, _ = resample_setup(num_samps)
        benchmark(
            self.cpu_version, cpu_sig, resample_num_samps, window=window,
        )

    def bench_resample_gpu(
        self, resample_setup, benchmark, num_samps, resample_num_samps, window
    ):

        cpu_sig, gpu_sig = resample_setup(num_samps)
        # Variable output holds result from final cusignal.resample
        # It is not copied back until assert to so timing is not impacted
        output = benchmark(
            cusignal.resample, gpu_sig, resample_num_samps, window=window
        )

        key = self.cpu_version(cpu_sig, resample_num_samps, window=window)
        assert array_equal(cp.asnumpy(output), key)
```

By adding `@pytest.mark.benchmark(group="Resample")` we are able to group all benchmarks from this class together in the output. 

grouping

All pytest parametrize calls are made to be identical to one in `test/test_signaltools.py`, but could be different. This allows multiple benchmarks to be ran in a single class. 

CPU (signal) and GPU (cusignal) functions are called from different definitions
```python
def bench_resample_cpu(
        self, resample_setup, benchmark, num_samps, resample_num_samps, window
    ):
        ...
def bench_resample_gpu(
        self, resample_setup, benchmark, num_samps, resample_num_samps, window
    ):
        ...
```

In the `bench_resample_cpu`, we call `cpu_version` which actually calls our signal function. This was done so it be called again by the `bench_resample_gpu` for correctness check and eliminate copy/paste issues. Notice that the correctness check is executed after the GPU benchmark to prevent copies from the device to host and affect performance measurements.

Next, to eliminate code redundancy, `@pytext.fixtures() is used when possible. In this PR, it is generally used during data generation for signal/cusignal functions. In our **BenchResample** example, see that `resample_setup` is a parameter to each benchmark. You will find that fixture in `conftest.py`. By scoping it with _session_, it will be executed once and shared with all benchmarks that require it. This also speeds up overall benchmark runtime.

```python
@pytest.fixture(scope="session")
def resample_setup():
    def _generate(arg):

        cpu_time = np.linspace(0, 10, endpoint=False)
        cpu_sig = np.cos(-(cpu_time ** 2) / 6.0)
        gpu_sig = cp.asarray(cpu_sig)

        return cpu_sig, gpu_sig

    return _generate
```

### Usage
`pytest` must be ran in `cusignal/python` to read `pytest.ini`.

Run defaults ---> `pytest -v` will skip all benchmarks and only run correctness test

Run benchmarks ---> `pytest -v --benchmark-only` will skip all correctness test

### CODE REVIEW

**Comment by mnicely** [comment]
@awthomp @BradReesWork 
Is it possible to add pytest-benchmark to the Git gpuCI build? I think that's why it's failing a few tests.

**Comment by awthomp** [comment]
@raydouglass Do you have any ideas on how to include these pytest benchmarks and pass CI?

**Comment by BradReesWork** [comment]
rerun tests

**Comment by BradReesWork** [comment]
@mnicely  looks you need to include pytest-benchmark to get some of the new arguments to work

**Comment by mnicely** [comment]
@BradReesWork Okay, I've added `import pytest-benchmark` to each file. Lets see if that works.

**Comment by rlratzel** [comment]
> @BradReesWork Okay, I've added `import pytest-benchmark` to each file. Lets see if that works.

I think @BradReesWork meant that the `pytest-benchmark` python package needs to be installed in the CI environment. There's a workaround you can do to install packages at CI time yourself (add a conda/pip install step in the `ci/gpu/build.sh`), but it's best to get Ops' approval.  Longer-term, Ops will probably add `pytest-benchmark` to the CI container and you won't need to do the install step.  @raydouglass will be able to comment further.

**Comment by mnicely** [comment]
@rlratzel Oh okay. Thanks for clarifying! Do you think it's okay to do the workaround for this PR and then submit a official request for future PRs?

**Comment by rlratzel** [comment]
> @rlratzel Oh okay. Thanks for clarifying! Do you think it's okay to do the workaround for this PR and then submit a official request for future PRs?

I think it would be okay, especially for this since it's a fairly benign package and doesn't add (I don't think) potentially conflicting dependencies.  There's examples of this in other `ci/gpu/build.sh` scripts if you want to see the pattern to follow.  cc @raydouglass

**Comment by BradReesWork** [comment]
@rlratzel thanks for adding pytest to the package

**Pull request merged**
