### PR TITLE
[REVIEW] Reorganize Jupyter notebooks to match code reorg

### PR DESCRIPTION
**Pull request by awthomp**
Closes https://github.com/rapidsai/cusignal/issues/85

No new functional changes, just a reorganization of the Jupyter notebooks to match new code organization introduced in v0.14.

### CODE REVIEW

**Comment by GPUtester** [comment]
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

**Comment by awthomp** [comment]
rerun tests

**Comment by awthomp** [comment]
@BradReesWork -- any idea why the pr-builder is failing here? The flake8 style check is failing, but that didn't typically cause the pr-build to fail.

**Comment by awthomp** [comment]
rerun tests

**Pull request merged**
