### PR TITLE
[REVIEW] Refactor _signaltools.py to new Numba/CuPy framework.

### PR DESCRIPTION
**Pull request by mnicely**
This PR does the following

1. Refactor `_signaltools.py` to utilize the new Numba/CuPy framework we added in `_upfirdn.py`. This will allow us to added CuPy kernels next
2. With (1), added type specialization to all Numba kernels
3. Reduces the number of registers per kernel from 64 to 32.

### CODE REVIEW

**Comment by mnicely** [comment]
Performance numbers after refactorization. 

Pre-refactor
```bash
------------------------------------------------------------------------------------------------ benchmark 'Convolve2d': 18 tests ------------------------------------------------------------------------------------------------
Name (time in us)                                   Min                    Max                  Mean                StdDev                Median                 IQR            Outliers         OPS            Rounds  Iterations
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
bench_convolve2d_gpu[valid-symm-5-256]         510.2240 (1.0)      15,333.3480 (26.26)      571.9330 (1.10)       383.8809 (79.14)      521.2340 (1.00)       9.3978 (2.20)       72;344  1,748.4564 (0.91)       1933           1
bench_convolve2d_gpu[valid-wrap-5-256]         511.6850 (1.00)        583.8680 (1.0)        519.9893 (1.0)          4.8505 (1.0)        519.4940 (1.0)        4.2635 (1.0)        275;59  1,923.1165 (1.0)        1935           1
bench_convolve2d_gpu[valid-fill-5-256]         511.8660 (1.00)      7,813.9960 (13.38)      572.2272 (1.10)       293.1461 (60.44)      520.5650 (1.00)       8.7820 (2.06)       90;369  1,747.5577 (0.91)       1935           1
bench_convolve2d_gpu[valid-symm-100-256]       513.9480 (1.01)     33,035.2710 (56.58)    1,526.7744 (2.94)       851.7301 (175.60)   1,680.8205 (3.24)      39.5810 (9.28)      305;477    654.9756 (0.34)       1930           1
bench_convolve2d_gpu[valid-fill-100-256]       514.1020 (1.01)      9,677.4270 (16.57)    1,552.3711 (2.99)       532.2713 (109.74)   1,665.1690 (3.21)      20.0863 (4.71)      365;555    644.1758 (0.33)       1923           1
bench_convolve2d_gpu[valid-wrap-100-256]       515.2980 (1.01)     26,289.8050 (45.03)    1,651.3394 (3.18)       937.2897 (193.24)   1,705.6270 (3.28)     358.8790 (84.17)     300;381    605.5690 (0.31)       1938           1
bench_convolve2d_gpu[full-fill-5-256]          635.2670 (1.25)     14,259.9010 (24.42)      713.8664 (1.37)       463.6417 (95.59)      647.1130 (1.25)      13.9065 (3.26)       59;225  1,400.8223 (0.73)       1517           1
bench_convolve2d_gpu[full-fill-100-256]        636.6020 (1.25)     44,891.0620 (76.89)    5,916.0973 (11.38)    2,463.1392 (507.81)   6,158.3765 (11.85)     58.7315 (13.78)     154;342    169.0304 (0.09)       1564           1
bench_convolve2d_gpu[same-fill-100-256]        646.5370 (1.27)     41,246.0190 (70.64)    3,118.7860 (6.00)     1,399.0277 (288.43)   3,270.7890 (6.30)      26.7110 (6.27)      166;400    320.6376 (0.17)       1536           1
bench_convolve2d_gpu[same-fill-5-256]          647.1240 (1.27)     21,469.7490 (36.77)      722.3554 (1.39)       613.8349 (126.55)     655.7870 (1.26)      12.7440 (2.99)       37;266  1,384.3602 (0.72)       1542           1
bench_convolve2d_gpu[full-wrap-5-256]          828.4980 (1.62)      1,444.1390 (2.47)       930.4144 (1.79)        67.3899 (13.89)      922.8130 (1.78)      10.0715 (2.36)        52;95  1,074.7899 (0.56)       1123           1
bench_convolve2d_gpu[full-symm-5-256]          830.2290 (1.63)      9,621.5270 (16.48)    1,013.7068 (1.95)       440.6848 (90.85)      925.5930 (1.78)      17.7040 (4.15)       61;230    986.4785 (0.51)       1103           1
bench_convolve2d_gpu[same-symm-5-256]          830.3560 (1.63)      1,363.4320 (2.34)       922.9753 (1.77)        29.2591 (6.03)       921.0910 (1.77)      10.2490 (2.40)        66;77  1,083.4526 (0.56)       1104           1
bench_convolve2d_gpu[same-wrap-5-256]          831.1370 (1.63)      5,935.4890 (10.17)    1,021.7239 (1.96)       369.6598 (76.21)      924.1815 (1.78)      20.7840 (4.87)       70;274    978.7380 (0.51)       1100           1
bench_convolve2d_gpu[same-wrap-100-256]      3,914.5930 (7.67)     10,156.3130 (17.39)    4,211.4239 (8.10)       479.8311 (98.92)    4,085.6320 (7.86)      66.1555 (15.52)      71;152    237.4494 (0.12)       1053           1
bench_convolve2d_gpu[same-symm-100-256]      3,930.4090 (7.70)      9,289.1910 (15.91)    4,269.3678 (8.21)       527.1550 (108.68)   4,128.2810 (7.95)      72.2638 (16.95)      79;138    234.2267 (0.12)        941           1
bench_convolve2d_gpu[full-wrap-100-256]      6,897.2370 (13.52)    31,018.7400 (53.13)    7,285.2016 (14.01)    1,174.7039 (242.18)   7,058.4005 (13.59)     20.6335 (4.84)       31;117    137.2646 (0.07)        552           1
bench_convolve2d_gpu[full-symm-100-256]      6,901.0070 (13.53)    39,261.4920 (67.24)    7,301.4274 (14.04)    1,379.2833 (284.36)   7,065.7780 (13.60)     13.0065 (3.05)       37;165    136.9595 (0.07)        843           1
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

------------------------------------------------------------------------------------------------ benchmark 'Correlate2d': 18 tests ------------------------------------------------------------------------------------------------
Name (time in us)                                    Min                    Max                  Mean                StdDev                Median                 IQR            Outliers         OPS            Rounds  Iterations
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
bench_correlate2d_gpu[valid-wrap-5-256]         513.3330 (1.0)      17,201.1460 (30.09)      572.1528 (1.10)       451.9519 (117.45)     521.5820 (1.00)       7.3310 (1.73)       48;322  1,747.7848 (0.91)       1921           1
bench_correlate2d_gpu[valid-wrap-100-256]       513.4460 (1.00)     37,261.7010 (65.17)    1,520.8621 (2.91)       921.8817 (239.56)   1,673.4550 (3.21)      23.9982 (5.67)      283;494    657.5218 (0.34)       1929           1
bench_correlate2d_gpu[valid-fill-5-256]         514.3820 (1.00)     14,936.8660 (26.13)      574.0838 (1.10)       408.4802 (106.15)     523.4085 (1.00)       8.1730 (1.93)       53;297  1,741.9059 (0.91)       1922           1
bench_correlate2d_gpu[valid-symm-5-256]         514.4120 (1.00)        571.7280 (1.0)        521.7597 (1.0)          3.8482 (1.0)        521.3160 (1.0)        4.2300 (1.0)        431;46  1,916.5909 (1.0)        1922           1
bench_correlate2d_gpu[valid-symm-100-256]       515.2740 (1.00)     20,015.0360 (35.01)    1,535.0158 (2.94)       709.2960 (184.32)   1,677.6560 (3.22)      97.5280 (23.06)     325;500    651.4591 (0.34)       1922           1
bench_correlate2d_gpu[valid-fill-100-256]       516.8210 (1.01)     41,200.3440 (72.06)    1,529.9691 (2.93)     1,029.9279 (267.64)   1,667.2765 (3.20)      43.4215 (10.27)       7;484    653.6080 (0.34)       1920           1
bench_correlate2d_gpu[full-fill-5-256]          631.1470 (1.23)      8,252.6560 (14.43)      702.6754 (1.35)       358.7532 (93.23)      639.7100 (1.23)       7.5010 (1.77)       72;257  1,423.1322 (0.74)       1572           1
bench_correlate2d_gpu[full-fill-100-256]        637.2760 (1.24)     53,139.3930 (92.95)    6,167.4009 (11.82)    2,577.0833 (669.69)   6,376.5270 (12.23)    256.1610 (60.56)     166;282    162.1429 (0.08)       1558           1
bench_correlate2d_gpu[same-fill-5-256]          643.1740 (1.25)     17,520.5990 (30.64)      710.0926 (1.36)       506.4890 (131.62)     650.5470 (1.25)       7.5278 (1.78)       54;211  1,408.2671 (0.73)       1537           1
bench_correlate2d_gpu[same-fill-100-256]        646.7530 (1.26)     38,736.7920 (67.75)    3,195.6841 (6.12)     1,439.6151 (374.10)   3,341.2790 (6.41)     121.0445 (28.62)     164;246    312.9220 (0.16)       1528           1
bench_correlate2d_gpu[same-wrap-5-256]          827.2430 (1.61)      1,675.4340 (2.93)       921.2421 (1.77)        30.9059 (8.03)       921.5240 (1.77)      10.3455 (2.45)        43;61  1,085.4910 (0.57)       1105           1
bench_correlate2d_gpu[same-symm-5-256]          831.7930 (1.62)     12,938.7350 (22.63)    1,010.6727 (1.94)       615.6276 (159.98)     923.1270 (1.77)      15.2415 (3.60)       49;216    989.4400 (0.52)       1183           1
bench_correlate2d_gpu[full-wrap-5-256]          835.5890 (1.63)      1,329.2750 (2.33)       926.2752 (1.78)        27.9575 (7.27)       923.3630 (1.77)      11.7510 (2.78)       81;125  1,079.5928 (0.56)       1098           1
bench_correlate2d_gpu[full-symm-5-256]          842.3170 (1.64)      1,129.7000 (1.98)       928.5555 (1.78)        20.4641 (5.32)       924.8250 (1.77)      15.1653 (3.59)       178;91  1,076.9415 (0.56)       1125           1
bench_correlate2d_gpu[same-wrap-100-256]      3,852.3210 (7.50)     14,806.6290 (25.90)    4,268.0580 (8.18)       698.9350 (181.63)   4,127.3910 (7.92)     117.2280 (27.71)      56;106    234.2986 (0.12)        942           1
bench_correlate2d_gpu[same-symm-100-256]      3,859.9840 (7.52)     39,131.1580 (68.44)    4,311.6184 (8.26)     1,359.9556 (353.40)   4,153.8660 (7.97)      77.0693 (18.22)      17;132    231.9315 (0.12)        939           1
bench_correlate2d_gpu[full-symm-100-256]      6,945.8410 (13.53)    25,385.0130 (44.40)    7,533.7652 (14.44)    1,335.8629 (347.14)   7,288.2110 (13.98)    232.1215 (54.88)       38;83    132.7358 (0.07)        867           1
bench_correlate2d_gpu[full-wrap-100-256]      6,949.7780 (13.54)    13,981.4920 (24.45)    7,451.6177 (14.28)      606.5891 (157.63)   7,325.2910 (14.05)    117.3285 (27.74)       30;42    134.1990 (0.07)        399           1
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
```

After refactor
```bash
------------------------------------------------------------------------------------------------ benchmark 'Convolve2d': 18 tests ------------------------------------------------------------------------------------------------
Name (time in us)                                   Min                    Max                  Mean                StdDev                Median                 IQR            Outliers         OPS            Rounds  Iterations
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
bench_convolve2d_gpu[valid-symm-5-256]         289.3570 (1.0)         470.5760 (1.0)        299.8174 (1.0)         20.8994 (1.0)        294.0705 (1.0)        2.8040 (1.0)       255;429  3,335.3633 (1.0)        3390           1
bench_convolve2d_gpu[valid-fill-100-256]       291.0750 (1.01)     39,555.3130 (84.06)    1,718.1731 (5.73)     1,004.5103 (48.06)    1,798.2900 (6.12)      29.3343 (10.46)     348;758    582.0135 (0.17)       3383           1
bench_convolve2d_gpu[valid-wrap-5-256]         291.0810 (1.01)      6,733.8600 (14.31)      335.5837 (1.12)       203.8530 (9.75)       296.4200 (1.01)      11.2420 (4.01)      121;517  2,979.8823 (0.89)       3017           1
bench_convolve2d_gpu[valid-wrap-100-256]       291.3480 (1.01)     25,356.8570 (53.88)    1,713.2760 (5.71)       772.7803 (36.98)    1,802.1360 (6.13)      24.9540 (8.90)      351;792    583.6771 (0.17)       3351           1
bench_convolve2d_gpu[valid-symm-100-256]       291.6400 (1.01)     32,091.9010 (68.20)    1,761.0148 (5.87)       941.7382 (45.06)    1,845.2820 (6.27)      57.6167 (20.55)     356;617    567.8544 (0.17)       3393           1
bench_convolve2d_gpu[valid-fill-5-256]         292.7430 (1.01)     14,087.3250 (29.94)      332.3826 (1.11)       318.1229 (15.22)      302.8065 (1.03)       4.7920 (1.71)       32;545  3,008.5815 (0.90)       3314           1
bench_convolve2d_gpu[same-fill-5-256]          410.9540 (1.42)        637.5710 (1.35)       425.8010 (1.42)        28.7972 (1.38)       416.5360 (1.42)       4.4903 (1.60)      215;323  2,348.5152 (0.70)       2401           1
bench_convolve2d_gpu[same-fill-100-256]        412.5610 (1.43)     39,259.9070 (83.43)    3,695.8789 (12.33)    1,474.8376 (70.57)    3,790.8820 (12.89)    206.9310 (73.80)     214;295    270.5716 (0.08)       2409           1
bench_convolve2d_gpu[full-fill-5-256]          416.7480 (1.44)     31,754.1690 (67.48)      469.2916 (1.57)       682.8110 (32.67)      424.9395 (1.45)       8.4200 (3.00)        9;353  2,130.8715 (0.64)       2328           1
bench_convolve2d_gpu[full-fill-100-256]        417.5240 (1.44)     43,121.4420 (91.64)    6,389.9165 (21.31)    2,019.1906 (96.61)    6,549.3160 (22.27)     94.1055 (33.56)     192;335    156.4966 (0.05)       2379           1
bench_convolve2d_gpu[full-wrap-5-256]          603.8140 (2.09)      1,327.3670 (2.82)       615.6243 (2.05)        36.0608 (1.73)       610.3810 (2.08)       4.3390 (1.55)       30;142  1,624.3673 (0.49)       1622           1
bench_convolve2d_gpu[full-symm-5-256]          607.7200 (2.10)     14,550.7470 (30.92)      686.1686 (2.29)       455.0175 (21.77)      615.4170 (2.09)      11.5750 (4.13)       60;297  1,457.3677 (0.44)       1625           1
bench_convolve2d_gpu[same-wrap-5-256]          611.7380 (2.11)     21,033.0840 (44.70)      691.8494 (2.31)       578.4854 (27.68)      617.9800 (2.10)      10.9822 (3.92)       63;289  1,445.4012 (0.43)       1623           1
bench_convolve2d_gpu[same-symm-5-256]          612.7590 (2.12)      1,108.6150 (2.36)       633.4309 (2.11)        47.6948 (2.28)       619.7770 (2.11)       5.6733 (2.02)       83;264  1,578.7042 (0.47)       1555           1
bench_convolve2d_gpu[same-wrap-100-256]      3,912.4340 (13.52)    14,361.6620 (30.52)    4,531.6651 (15.11)      643.9760 (30.81)    4,430.3930 (15.07)    169.5663 (60.47)      75;136    220.6694 (0.07)       1191           1
bench_convolve2d_gpu[same-symm-100-256]      4,042.5770 (13.97)    19,196.8160 (40.79)    4,573.6260 (15.25)      803.4576 (38.44)    4,434.7250 (15.08)    137.1740 (48.92)      69;166    218.6449 (0.07)       1139           1
bench_convolve2d_gpu[full-symm-100-256]      7,063.3340 (24.41)    14,383.6150 (30.57)    7,544.1684 (25.16)      556.3906 (26.62)    7,407.1680 (25.19)     93.7680 (33.44)      82;142    132.5527 (0.04)       1087           1
bench_convolve2d_gpu[full-wrap-100-256]      7,186.3330 (24.84)    28,378.1610 (60.31)    7,583.5002 (25.29)    1,209.0888 (57.85)    7,365.3980 (25.05)     60.6180 (21.62)      25;116    131.8652 (0.04)        633           1
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

------------------------------------------------------------------------------------------------ benchmark 'Correlate2d': 18 tests ------------------------------------------------------------------------------------------------
Name (time in us)                                    Min                    Max                  Mean                StdDev                Median                 IQR            Outliers         OPS            Rounds  Iterations
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
bench_correlate2d_gpu[valid-fill-5-256]         289.8440 (1.0)         469.2490 (1.0)        299.8807 (1.01)        20.0610 (3.50)       294.4315 (1.0)        2.7590 (1.27)      261;384  3,334.6590 (0.99)       3376           1
bench_correlate2d_gpu[valid-symm-5-256]         290.6350 (1.00)        543.3010 (1.16)       296.1015 (1.0)          5.7306 (1.0)        295.3565 (1.00)       2.1700 (1.0)       114;260  3,377.2201 (1.0)        3356           1
bench_correlate2d_gpu[valid-wrap-5-256]         293.2960 (1.01)        545.2400 (1.16)       303.2287 (1.02)        30.6294 (5.34)       297.6380 (1.01)       2.5895 (1.19)       65;335  3,297.8414 (0.98)       3340           1
bench_correlate2d_gpu[valid-symm-100-256]       293.7680 (1.01)     34,678.7460 (73.90)    1,922.7692 (6.49)     1,008.8000 (176.04)   2,024.8570 (6.88)      75.2370 (34.67)     318;716    520.0832 (0.15)       3366           1
bench_correlate2d_gpu[valid-fill-100-256]       294.4860 (1.02)     43,762.9800 (93.26)    1,883.7540 (6.36)     1,162.0444 (202.78)   1,968.9140 (6.69)      83.9130 (38.67)     326;575    530.8549 (0.16)       3366           1
bench_correlate2d_gpu[valid-wrap-100-256]       303.8300 (1.05)     29,100.6200 (62.02)    1,911.8953 (6.46)       867.0968 (151.31)   1,995.9900 (6.78)      78.4578 (36.16)     369;635    523.0412 (0.15)       3345           1
bench_correlate2d_gpu[full-fill-5-256]          416.1020 (1.44)        895.4670 (1.91)       428.3527 (1.45)        29.6915 (5.18)       420.9380 (1.43)       4.2977 (1.98)      133;282  2,334.5250 (0.69)       2369           1
bench_correlate2d_gpu[full-fill-100-256]        419.7600 (1.45)     48,226.9290 (102.77)   7,447.0345 (25.15)    2,322.9401 (405.35)   7,605.7280 (25.83)    332.8787 (153.40)    216;291    134.2816 (0.04)       2371           1
bench_correlate2d_gpu[same-fill-5-256]          421.1660 (1.45)        726.1020 (1.55)       428.4793 (1.45)        16.2861 (2.84)       426.4300 (1.45)       3.1037 (1.43)       37;170  2,333.8350 (0.69)       2359           1
bench_correlate2d_gpu[same-fill-100-256]        426.9120 (1.47)     50,810.3820 (108.28)   3,982.7944 (13.45)    1,843.8557 (321.75)   4,089.8880 (13.89)    156.3610 (72.06)     188;388    251.0800 (0.07)       2335           1
bench_correlate2d_gpu[full-symm-5-256]          599.7500 (2.07)      6,602.0830 (14.07)      674.0723 (2.28)       343.1494 (59.88)      607.2810 (2.06)       8.6010 (3.96)       68;328  1,483.5204 (0.44)       1656           1
bench_correlate2d_gpu[same-wrap-5-256]          603.1310 (2.08)      1,307.0180 (2.79)       631.8394 (2.13)        52.5475 (9.17)       608.7730 (2.07)      12.4580 (5.74)      255;268  1,582.6806 (0.47)       1642           1
bench_correlate2d_gpu[same-symm-5-256]          603.7990 (2.08)      6,925.6470 (14.76)      635.5537 (2.15)       261.9477 (45.71)      609.7730 (2.07)       3.3270 (1.53)       28;124  1,573.4311 (0.47)       1642           1
bench_correlate2d_gpu[full-wrap-5-256]          608.0400 (2.10)     13,025.6710 (27.76)      700.8097 (2.37)       476.8657 (83.21)      614.7330 (2.09)      65.0760 (29.99)      65;139  1,426.9209 (0.42)       1640           1
bench_correlate2d_gpu[same-wrap-100-256]      4,012.2520 (13.84)    28,239.4220 (60.18)    4,776.9270 (16.13)      851.5763 (148.60)   4,694.7670 (15.95)    156.2385 (72.00)      46;179    209.3396 (0.06)       1184           1
bench_correlate2d_gpu[same-symm-100-256]      4,045.4330 (13.96)     5,410.6700 (11.53)    4,509.4683 (15.23)      242.4697 (42.31)    4,502.0000 (15.29)    258.9298 (119.32)       96;7    221.7556 (0.07)        305           1
bench_correlate2d_gpu[full-wrap-100-256]      7,441.9810 (25.68)    42,325.2290 (90.20)    8,601.1267 (29.05)    1,244.4556 (217.16)   8,476.3290 (28.79)    333.7595 (153.81)     46;136    116.2638 (0.03)       1101           1
bench_correlate2d_gpu[full-symm-100-256]      7,652.4150 (26.40)    26,369.2740 (56.19)    8,595.7713 (29.03)    1,025.7598 (179.00)   8,428.3790 (28.63)    307.3635 (141.64)     75;120    116.3363 (0.03)       1241           1
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

**Comment by awthomp** [comment]
@gmarkall -- We're getting to the point where I'm not going to be able to provide a good review of @mnicely's awesome work with fully leveraging Numba and CuPy. Do you mind taking a look at what Matt's done here -- refactoring the code to adopt the new Numba/CuPy framework and let me know what you think?

@dicta -- I'd appreciate your feedback too.

**Comment by mnicely** [comment]
@awthomp @dicta @gmarkall 
I unintentionally pushed pytest-benchmark into this PR. I had the branches merged on my local machine looking for bottlenecks.

I believe I fixed the issue. I apologize for any issues it might have caused!

**Comment by gmarkall** [comment]
@awthomp I have been looking at this, over the past couple of days - I know the PR is already merged, but there isn't anything here that jumps out from me as being something that could be done better with current Numba - I have been looking for ways to reduce the register usage with Numba, as it still has a habit of using int64 for many indices when an int32 would suffice. 

I've been experimenting with making the `locals` kwarg to the `jit` decorator work with CUDA - this allows the types of local variables to be specified as well as the types of arguments, but unfortunately it doesn't seem to help in this case (arithmetic operations are still typed as 64-bit, then cast to 32 bits). (For reference, the `locals` kwarg is documented for the CPU target here: https://numba.pydata.org/numba-doc/dev/reference/jit-compilation.html?highlight=locals#numba.jit ).

There are other changes to Numba and the CUDA target potentially further over the horizon that might help with this (some changes to the typing that allow 32-bit ints to be more preferred by type inference) but it will be a while before I can try these.

**Pull request merged**
