### PR TITLE
[REVIEW] Code Refactor

### PR DESCRIPTION
**Pull request by mnicely**
### Info 

Initial development for cuSignal code refactor.

### CODE REVIEW

**Comment by GPUtester** [comment]
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

**Comment by mnicely** [comment]
# Info
This PR makes an attempts the following by refactoring the code base.
1. Simplify code by removing reduction kernels
2. Improve user experience
3. Improve compile time where possible

## Implementing (1)
The following functions exist in multiple modules.
1. `_stream_cupy_to_numba` (will be removed in 0.15)
2. `precompile_kernels`
2. `_populate_kernel_cache`
3. `_get_backend_kernel`

File _compile_kernels.py is created to house `_stream_cupy_to_numba`, `precompile_kernels`, `_populate_kernel_cache`.

(1) Moving `_stream_cupy_to_numba` is a straightforward port.

(2) Moving `precompile_kernels` is nearly straightforward, but because each kernel takes only accepts an unique set of data types additional logic is added. 

The following dictionaries are added to hold each unique set
```python
_SUPPORTED_TYPES_CONVOLVE = {
    np.int32: [int32, "int"],
    np.int64: [int64, "long int"],
    np.float32: [float32, "float"],
    np.float64: [float64, "double"],
    np.complex64: [complex64, "complex<float>"],
    np.complex128: [complex128, "complex<double>"],
}

_SUPPORTED_TYPES_LFILTER = {
    np.float32: [float32, "float"],
    np.float64: [float64, "double"],
}

_SUPPORTED_TYPES_LOMBSCARGLE = {
    np.float32: [float32, "float"],
    np.float64: [float64, "double"],
}

_SUPPORTED_TYPES_UPFIRDN = {
    np.float32: [float32, "float"],
    np.float64: [float64, "double"],
    np.complex64: [complex64, "complex<float>"],
    np.complex128: [complex128, "complex<double>"],
}
```

Next, inputs provided to `precompile_kernels` are validated before preceding to `_populate_kernel_cache`

(3) Porting `_populate_kernel_cache` is a little more complicated. Adding all possible kernels to a single module requires the following update to the `GPUKernel` class.

```python
class GPUKernel(Enum):
    CORRELATE = 0
    CONVOLVE = 1
    CORRELATE2D = 2
    CONVOLVE2D = 3
    LFILTER = 4
    LOMBSCARGLE = 5
    UPFIRDN = 6
    UPFIRDN2D = 7
```

Notice that **UPFIRDN2D** was added back to enable simplier code interface. This does not affect performance but requires the user to select it, during precompile, if the input data is 2 dimension. This mimics the original implementation of **upfirdn**.

In order to prevent circular importing issues, kernels have been broken into separate files. 
```bash
_lfilter_kernels.py
_signaltools_kernels.py
_spectral_kernels.py
_upfirdn_kernels.py
```

Note: For now, I'm leaving `_get_backend_kernel` in each module. My rationale is that it is used to choose a compiled kernel, but has nothing to do with the compiling itself.

### Maintain global dictionaries
Previously, each module maintained a separate cache dictionary to house compile kernels. Which all kernels being compiled in a single module, a single global dictionary must be created and passed among modules. This is accomplished be creating `caches.py` and importing it before `compile_kernels'. Implemented according to https://docs.python.org/3/faq/programming.html#how-do-i-share-global-variables-across-modules.

## Implementing (2)
Previously, users wanting to precompile kernels had to include the module name in the call. Like so
```python
cusignal._signaltools.precompile_kernels()
```

This has now been replaced with
```python
cusignal.precompile_kernels()
```

## Implementing (3)
In order to speed up compile time of individual kernels during runtime, each CuPy kernel has been separated into individual modules. This is because when CuPy Raw Modules are loading all kernels in the module are compiled.

## Benchmarks
All benchmarks passed with no reduction in performance.

**Comment by awthomp** [comment]
I'm working my way through the PR, but one immediate change that would be nice is to have the kernels grouped in their respective modules. Presently, we have, in `python/cusignal`:
* `_lfilter_kernels`
* `_caches.py`
* `_compile_kernels.py`
* `_signaltools_kernels.py`
* `_spectral_kernels.py`
* `_upfirdn_kernels.py`

Let's definitely put:
* `_lfilter_kernels` in `python/cusignal/filtering`
* `_spectral_kernels` in `python/cusignal/spectral`
* `_upfridn_kernels.py` in `python/cusignal/filtering`

We'll need to split up `_spectral_kernels.py`, create new groupings similar to the code structure currently in cusignal (e.g. most will go in `python/cusignal/convolution`).

As for `_compile_kernels.py` and `_caches.py`, I think we could put these in `python/cusignal/utils` or maybe create a new folder in `python/cusignal` called `_cuda`?

Let's get these files re-organized, and then dig into the UX.

**Comment by mnicely** [comment]
> I'm working my way through the PR, but one immediate change that would be nice is to have the kernels grouped in their respective modules. Presently, we have, in `python/cusignal`:
> 
> * `_lfilter_kernels`
> * `_caches.py`
> * `_compile_kernels.py`
> * `_signaltools_kernels.py`
> * `_spectral_kernels.py`
> * `_upfirdn_kernels.py`
> 
> Let's definitely put:
> 
> * `_lfilter_kernels` in `python/cusignal/filtering`
> * `_spectral_kernels` in `python/cusignal/spectral`
> * `_upfridn_kernels.py` in `python/cusignal/filtering`
> 
> We'll need to split up `_signaltools_kernels.py`, create new groupings similar to the code structure currently in cusignal (e.g. most will go in `python/cusignal/convolution`).
> 
> As for `_compile_kernels.py` and `_caches.py`, I think we could put these in `python/cusignal/utils` or maybe create a new folder in `python/cusignal` called `_cuda`?
> 
> Let's get these files re-organized, and then dig into the UX.

I believe are requested changes have been made.

**Comment by awthomp** [comment]
Hey @mnicely -- I apologize if I wasn't clear, but let's move all the unorganized private methods to our modules. I like that the kernels have been moved to their respective folders, but I'd like to see `_filtering.py` in the `filtering` folder, for example. 

So let's focus on `python/cusignal/convolution`. In this folder, I'd expect to see (with current naming conventions):
* `_convolve_kernels.py` - convolve raw CuPy CUDA
* `_correlate_kernels.py` - correlate raw CuPy CUDA
* `convolution_utils.py` - common convolution utils
* `convolve.py` - standard cusignal convolve definitions
* `correlate.py` - standard cusignal correlate definitions
* `_convolve.py` - CuPy/Numba CUDA helper/initialization for convolve
* `_correlate.py` - CuPy/Numba CUDA helper/initialization for correlate

I don't know the best way to organize the CUDA bits, but if I'm a developer coming across our project, I'd want to be able to quickly see what's CUDA vs what's Python. I think you could argue for merging the `_convolve.py` with `_convolve_kernels.py` or renaming this combination to `_convolve_cuda.py`.

I'm certainly open to other ideas, though!
That said, I think this structure is too confusing, and I'd like to see

**Comment by awthomp** [comment]
@mnicely and I chatted offline, and the current plan for the `precompile_kernels` API is the following:

* Remove Numba recompilation and caching. We are deprecating the Numba CUDA kernels in favor of raw CuPy CUDA kernels in 0.15, and feel learning and developing a new API to support a functionality that will soon disappear isn't valuable.

* Redesign the `precompile_kernels` to be more user friendly by changing the order of inputs to <name-of-function> then <numerical-precision> rather than the legacy implementation that switched these.

* Remove the GPUKernel class and instead input a string. Instead of `GPUKernel.CONVOLVE2D`, the user will specify `convolve2d`.

We're also supporting three different cases:

1. The user wants to precompile all kernels with all supported data-types
```python
import cusignal
cusignal.precompile_kernels()
```

2. The user wants to precompile a given function with all supported data-types
```python
import cusignal
cusignal.precompile_kernels('convolve2d')
```

3. The user wants to precompile a given function with specified data-types
```python
import cusignal
cusignal.precompile_kernels('convolve2d', [np.float32, np.float64])
```

We currently will not support the option to specifiy multiple functions, e.g:
```python
import cusignal
cusignal.precompile_kernels(['convolve2d', 'upfirdn'], [np.float32])
```

If the user wants to precompile multiple kernels, specify them in separate calls. Or compile all kernels.

A few things to think about:
* What do we default to if the user wants to compile at fp32 but inputs data with fp64?
* Do we want to allow for all kernels compiled with specified datatypes, e.g. ?

```python
import cusignal
cusignal.precompile_kernels([np.float32])
```

**Comment by mnicely** [comment]
> A few things to think about:
> 
> * What do we default to if the user wants to compile at fp32 but inputs data with fp64?
> * Do we want to allow for all kernels compiled with specified datatypes, e.g. ?
> 
> ```python
> import cusignal
> cusignal.precompile_kernels([np.float32])
> ```

1. If the data types do not match between precompiled kernels and runtime, kernels will be recompiled with runtime data type.
2. This functionality is already implemented :)

**Pull request merged**
