### PR TITLE
[PR-REVIEW] Reorg test and benchmark folders

### PR DESCRIPTION
**Pull request by mnicely**
## Info
This PR implements code reorg for #107. 

### Tests
`test_signaltools.py` to broken into the following files:
1. `test_convolution.py`
2. `test_filter_design.py`
3. `test_filtering.py`

`test_spectral.py` was moved to `test_spectral_analysis.py` to match spectral_analysis folder name.

The following files were added.
1. `test_acoustics.py`
2. `test_bsplines.py`
3. `test_peak_finding.py`

In the process, I discovered that there are functions that are not being tested.

1. **filtering**
- lfiltic
- detrend
- freq_shift

2. **filter_design**
- kaiser_beta
- kaiser_atten
- cmplx_sort

3. **peak_finding**
- argrelmin
- argrelmax
- argrelextrema

4. **acoustics**
- rceps
- cceps_unwrap
- cceps

5. **wavelets**
- qmf

6. **bsplines**
- gauss_spline
- cubic
- quadratic
- cspline1d

7. **spectral_analysis**
- vectorstrength

8. **windows**
- parzen (ADDED)
- chebwin (ADDED)
- get_window (ADDED)

### Benchmarks
`bench_signaltools.py` to broken into the following files:
1. `bench_convolution.py`
2. `bench_filter_design.py`
3. `bench_filtering.py`

`bench_spectral.py` was moved to `bench_spectral_analysis.py` to match spectral_analysis folder name.

The following files were added.
1. `bench_acoustics.py`
2. `bench_bsplines.py`
3. `bench_peak_finding.py`

In the process, I discovered that there are functions that are not being tested.

1. **filtering**
- lfiltic
- detrend
- freq_shift
- decimate (ADDED)

2. **filter_design**
- kaiser_beta
- kaiser_atten
- cmplx_sort

3. **peak_finding**
- argrelmin
- argrelmax
- argrelextrema

4. **acoustics**
- rceps
- cceps_unwrap
- cceps

5. **wavelets**
- qmf

6. **bsplines**
- gauss_spline
- cubic
- quadratic
- cspline1d

7. **spectral_analysis**
- vectorstrength

8. **windows**
- parzen (ADDED)
- chebwin (ADDED)
- get_window (ADDED)

### Additional changes
1. Benchmark results now sort on mean times (previously - min)

### CODE REVIEW

**Comment by GPUtester** [comment]
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

**Comment by awthomp** [comment]
rerun tests

**Comment by awthomp** [comment]
Closes https://github.com/rapidsai/cusignal/issues/107

**Comment by awthomp** [comment]
closes https://github.com/rapidsai/cusignal/issues/107

**Pull request merged**
