### PR TITLE
[PR-REVIEW] Remove cp_stream and autosync

### PR DESCRIPTION
**Pull request by mnicely**
### Info 
This PR is to solve #123. If a user passed in a non-default stream, it would be used by the kernel but not the memory transfers.

Propose removing `cp_stream` and `autosync` all together. These were initially integrated to allow users to control asynchronous functionality. This is much better suited at the application level.

### Current design
```python
stream = cp.cuda.stream.Stream(null=False, non_blocking=False)
gpu_lombscargle = cp.asnumpy(
    cusignal.lombscargle(d_x, d_y, d_f, cp_stream=stream, autosync=True)
)
```

### Proposed redesign
```python
stream = cp.cuda.stream.Stream(null=False, non_blocking=False)

stream.use()
gpu_lombscargle = cp.asnumpy(cusignal.lombscargle(d_x, d_y, d_f))
stream.synchronize()
```

### CODE REVIEW

**Comment by GPUtester** [comment]
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

**Comment by leofang** [comment]
Just curious, any reason to prefer `with cp_stream:` over `cp_stream.use()`? The latter saves one indentation level.

**Comment by mnicely** [comment]
@leofang I didn't have any particular reason. But when I compare the two, there are some performance difference. When using `cp_stream.use()` there's an extended delay on one of the `cudaMalloc`s that isn't there with `with cp_stream`, at least with this test case.

### `with cp_stream`
with-cp_stream

### `cp_stream.use`
cp_stream-use

### Test code
```python
    cp_stream.use() # or with cp_stream:
    x = asarray(x, dtype=cp.float64)
    y = asarray(y, dtype=cp.float64)
    freqs = asarray(freqs, dtype=cp.float64)
    pgram = cp.empty(freqs.shape[0], dtype=cp.float64)

    assert x.ndim == 1
    assert y.ndim == 1
    assert freqs.ndim == 1

    # Check input sizes
    if x.shape[0] != y.shape[0]:
        raise ValueError("Input arrays do not have the same size.")

    y_dot = cp.zeros(1, dtype=cp.float64)
    if normalize:
        cp.dot(y, y, out=y_dot)

    if precenter:
        y_in = y - y.mean()
    else:
        y_in = y

    _lombscargle(x, y_in, freqs, pgram, y_dot)

    if autosync is True:
        cp_stream.synchronize()

    return pgram
```

**Comment by mnicely** [comment]
@awthomp After further inspection, I believe we should completely remove `cp_stream` and `autosync`. They make cuSignal functions containing CuPy Raw Kernels distinctly different from the others. I think a much better, and cleaner, approach should be to allow the user to control streams at the application level to avoid any confusion and unexpected performance issues.

### Current design
```python
stream = cp.cuda.stream.Stream(null=False, non_blocking=False)
gpu_lombscargle = cp.asnumpy(
    cusignal.lombscargle(d_x, d_y, d_f, cp_stream=stream, autosync=True)
)
```

### Proposed redesign
```python
stream = cp.cuda.stream.Stream(null=False, non_blocking=False)

stream.use()
gpu_lombscargle = cp.asnumpy(cusignal.lombscargle(d_x, d_y, d_f))
stream.synchronize()
```

**Comment by leofang** [comment]
I will try to look into that later today.

**Comment by leofang** [comment]
Hi @mnicely 

> When using `cp_stream.use()` there's an extended delay on one of the `cudaMalloc`s that isn't there with `with cp_stream`, at least with this test case.

It sounds weird and should not happen. Are you using CuPy's default allocator? CuPy has its own memory pool so `cudaMalloc` should only be called when allocating the first GPU array or resizing the pool. I  used a very simplified code (perhaps too simplified?) and saw no difference in nvprof:
```python
import cupy as cp
from cupyx.time import repeat


def f():
    a = cp.empty((100000000,))
    a = cp.exp(a)
    del a


stream = cp.cuda.Stream()

#with stream:
#    print("with stream:", repeat(f, ()))

stream.use()
print("use stream:", repeat(f, ()))
```
Perhaps it's just a transient thing?

> I think a much better, and cleaner, approach should be to allow the user to control streams at the application level to avoid any confusion and unexpected performance issues.

I don't know the typical usage pattern in cuSignal, but this sounds reasonable to CuPy users.

**Pull request merged**
